// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let ylim = (-13.0, 23.0)
#let abc-style = (..abc-style, location: bottom + left, outset: 0.2em, fill: none)

// just use the blue for everything...
#let colors(i) = color-left

#let xaxis-major-ticks = (
  locs: (-1.0, 0.0, 1.0, 2.0),
  labels: ($−1$, $0$, $1$, $2$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (0.5,),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)
#let yaxis-major-ticks = (
  locs: (0.0, 1.0),
  labels: ($0$, $1$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: (0.5,),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let inset-0(xlim: (-0.51, 0.51), ylim: ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-0.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: colors(3),
    thickness: linewidth-very-narrow,
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: colors(3),
    thickness: linewidth-very-narrow,
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let stroke-line-3 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-0)
  // draw.collection(..collection-1)
  // draw.collection(..collection-2)
  // draw.line(..line-3)
  axes.spines(spines)
  axes.abc(..abc-style, location: top + center, 1)
}


#let inset-1(xlim: (-0.51, 0.51), ylim: ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-1.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: colors(3),
    thickness: linewidth-very-narrow,
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: colors(3),
    thickness: linewidth-very-narrow,
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let stroke-line-3 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-0)
  // draw.collection(..collection-1)
  // draw.collection(..collection-2)
  // draw.line(..line-3)
  axes.spines(spines)
  axes.abc(..abc-style, location: top + center, 2)
}


#let inset-2(xlim: (-0.51, 0.51), ylim: ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-2.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: colors(3),
    thickness: linewidth-very-narrow,
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: colors(3),
    thickness: linewidth-very-narrow,
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let stroke-line-3 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-0)
  // draw.collection(..collection-1)
  // draw.collection(..collection-2)
  // draw.line(..line-3)
  axes.spines(spines)
  axes.abc(..abc-style, location: top + center, 3)
}


#let axes-0(xlim: (-4.3, 4.3), ylim: (-0.04999479279485311, 1.0498906486919153), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 100% + 2.2em),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Offset $Delta slash t$]),
    ),
  )
  let label-yaxis = (
    position: (-14%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Occupation $n_L$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(-3, 5, step: 2),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-0.2, 0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2),
    labels: ($−0.2$, $0$, $0.2$, $0.4$, $0.6$, $0.8$, $1$, $1.2$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(5).map(y => y * 0.2 + 0.1),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: luma(30%),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = markers.circle(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-3 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-3 = markers.circle(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let stroke-line-5 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-5 = markers.circle(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-5 = (
    data: data.at("line-5"),
    stroke: stroke-line-5,
    marker: marker-line-5,
    transform: transform,
  )

  let properties-inset-0 = (position: (5.0%, 25.0%), shape: (25.0%, 25.0%))
  let properties-inset-1 = (position: (70.0%, 55.0%), shape: (25.0%, 25.0%))
  let properties-inset-2 = (position: (8.0%, 73.0%), shape: (25.0%, 25.0%))

  let shape = (4% / xscale, 4% / yscale)
  let shape = (1e-5, 1e-5)
  let indicator-inset-0 = (
    target: (
      position: (-1 - shape.at(0) / 2, 0.683446164489646 + shape.at(1) / 2),
      shape: shape,
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-0,
    connectors: (
      anchors: (bottom + right, top + right),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-1 = (
    target: (
      position: (0.5 - shape.at(0) / 2, 0.2271970304747089 + shape.at(1) / 2),
      shape: shape,
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-1,
    connectors: (
      anchors: (bottom + left, top + left),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-2 = (
    target: (
      position: (0 - shape.at(0) / 2, 1e-05 + shape.at(1) / 2),
      shape: shape,
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-2,
    connectors: (
      anchors: (bottom + right, top + right),
      stroke: inset-connector-stroke,
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  axes.inset-indicator(..indicator-inset-0)
  axes.inset-indicator(..indicator-inset-1)
  axes.inset-indicator(..indicator-inset-2)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-3)
  draw.line(..line-5)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.inset(..properties-inset-0, inset-0())
  axes.inset(..properties-inset-1, inset-1())
  axes.inset(..properties-inset-2, inset-2())
}


#let axes-1(xlim: (-0.1, 1.1), ylim: (-0.1, 1.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let stroke-line-0 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: ylim.map(y => (0.25, y)),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 1)
}


#let axes-2(xlim: (-0.1, 1.1), ylim: (-0.1, 1.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let stroke-line-0 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: ylim.map(y => (0.25, y)),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 2)
}


#let axes-3(xlim: (-0.1, 1.1), ylim: (-0.1, 1.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")

  let label-xaxis = (
    position: (50.0%, 100% + 2.2em),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Time $tau slash (h slash t)$]),
    ),
  )

  let stroke-line-0 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (2.22pt, 0.96pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: ylim.map(y => (0.25, y)),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 3)
}


#let grid-0() = {
  let padding = (left: 12.5%, right: 0.9%, top: 1.2%, bottom: 15%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (3fr, 1fr),
        rows: (1fr, 1fr, 1fr),
        column-gutter: (7.5%,),
        row-gutter: gutter,
        axes.cell(
          position: (0, 0),
          shape: (1, 3),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (1, 1),
          shape: (1, 1),
          axes-2(),
        ),
        axes.cell(
          position: (1, 2),
          shape: (1, 1),
          axes-3(),
        ),
      ),
    ),
  )
}


#let figure(width: 10cm, height: 7.18cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
