// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let inset-0(xlim: (-0.05, 2.05), ylim: (-0.05, 1.05), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-0.json")

  let xaxis-major-ticks = (
    locs: (0, 1, 2),
    labels: (),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(0, 11).map(x => x / 5),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0, 1),
    labels: ($0$, $1$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(6).map(y => y / 5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: color-singlet,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-right,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-left,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let inset-1(xlim: (-0.05, 2.05), ylim: (-0.05, 1.05), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-1.json")

  let label-xaxis = (
    position: (50.0%, 124.209%),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Time $tau slash (h slash t)$]),
    ),
  )
  let xaxis-major-ticks = (
    locs: (0, 1, 2),
    labels: ($0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(0, 11).map(x => x / 5),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0, 1),
    labels: ($0$, $1$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(6).map(y => y / 5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: color-singlet,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-right,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-left,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
}


#let axes-0(xlim: (-6.3, 6.3), ylim: (-16.824674507221165, 8.94502204393815), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111.62%),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Offset $Delta slash t$]),
    ),
  )
  let label-yaxis = (
    position: (-13.894%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Energy $epsilon slash t$]),
      ),
    ),
  )
  let secondary-label-yaxis = (
    position: (175%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [State composition]),
      ),
    ),
  )

  let xaxis-major-ticks = (
    locs: range(-6, 8, step: 2),
    labels: range(-6, 8, step: 2).map(x => $#x$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(-6, 8, step: 1).map(x => x + 1),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-20.0, -15.0, -10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−20$, $−15$, $−10$, $−5$, $0$, $5$, $10$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(5).map(y => y * 5 - 12.5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: gradient.linear(
      ..((color-left,) * 3),
      ..((color-right,) * 3),
    ),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-triplet,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: gradient.linear(
      color-singlet,
      color-singlet,
      color-right,
      color-left,
      color-singlet,
      color-singlet,
    ),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let stroke-line-3 = (
    paint: gradient.linear(
      ..((color-right,) * 2),
      ..((color-singlet,) * 2),
      ..((color-left,) * 2),
    ),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let state-label-positions = (-13.0, -1.2, 1.4, 6.2)
  let state-labels = range(4).map(i => {
    (
      position: transform((-5.8, state-label-positions.at(i))),
      body: place(left + horizon, text(size: 1em, fill: black, bottom-edge: "descender", [$epsilon_#(i + 1)$])),
    )
  })

  let properties-inset-0 = (position: (103.0%, 0.0%), shape: (60.0%, 48.0%))

  let properties-inset-1 = (position: (103.0%, 52.0%), shape: (60.0%, 48.0%))

  let indicator-inset-0 = (
    target: (
      position: (1.5, 2.6),
      shape: (1, 5),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-0,
    connectors: (
      anchors: (top + left, bottom + left),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-1 = (
    target: (
      position: (-0.5, -2.9),
      shape: (1, 3),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-1,
    connectors: (
      anchors: (top + left, bottom + left),
      stroke: inset-connector-stroke,
    ),
  )

  let marks = marks.with(outset: 0.3em)
  let basis-states = $marks(kets, color: #color-singlet) quad marks(kett, color: #color-triplet) quad marks(ketLL, color: #color-left) quad marks(ketRR, color: #color-right)$

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + center, dy: 5%, basis-states)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..secondary-label-yaxis)
  for label in state-labels { draw.text(..label) }
  axes.inset-indicator(..indicator-inset-0)
  axes.inset-indicator(..indicator-inset-1)
  axes.inset(..properties-inset-0, inset-0())
  axes.inset(..properties-inset-1, inset-1())
}


#let grid-0() = {
  let padding = (left: 10.0%, right: 40.0%, top: 3.0%, bottom: 15.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr,),
        rows: (1fr,),
        column-gutter: (),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
