// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let xaxis-major-ticks = (
  locs: (-100.0, -50.0, 0.0, 50.0, 100.0),
  labels: ($−100$, $−50$, $0$, $50$, $100$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (-25, 25),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)
#let yaxis-major-ticks = (
  locs: (-100.0, -50.0, 0.0, 50.0, 100.0),
  labels: ($−100$, $−50$, $0$, $50$, $100$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: (-25, 25),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let inset-0(
  xlim: (-62.90322580645162, 62.90322580645162),
  ylim: (62.90322580645162, -62.90322580645162),
  dpi: 100.0,
) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/inset-0-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 1)
}


#let inset-1(
  xlim: (-62.90322580645162, 62.90322580645162),
  ylim: (62.90322580645162, -62.90322580645162),
  dpi: 100.0,
) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-1.json")

  let label-xaxis = (
    position: (50.0%, 100.0% + 2.2em),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Position $x slash#unit[μm]$]),
    ),
  )

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/inset-1-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let axes-0(xlim: (-0.575, 2.175), ylim: (0.19, 0.91), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 100.0% + 2.2em),
    body: place(
      center + top,
      text(
        size: 1em,
        fill: black,
        [Glass-plate angle $gver slash degree$],
      ),
    ),
  )
  let label-yaxis = (
    position: (-15%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(
          size: 1em,
          fill: black,
          bottom-edge: "descender",
          [Signal constrast / a.u.],
        ),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0, 2.5),
    labels: ($−1$, $−0.5$, $0$, $0.5$, $1$, $1.5$, $2$, $2.5$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(5).map(x => x * 0.5 - 0.25),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
    labels: ($0.1$, $0.2$, $0.3$, $0.4$, $0.5$, $0.6$, $0.7$, $0.8$, $0.9$, $1$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(7).map(y => y * 0.1 + 0.25),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    fill: color.rgb("#0072b2ff"),
    stroke: black + linewidth-very-narrow,
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: color.rgb(0.0%, 44.706%, 69.804%, 100.0%),
    thickness: linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: color.rgb(0.0%, 44.706%, 69.804%, 100.0%),
    thickness: linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let properties-inset-0 = (
    position: (100.0% + gutter, 0.0%),
    shape: (50% - gutter / 2, 50% - gutter / 2),
  )

  let properties-inset-1 = (
    position: (100.0% + gutter, 50% + gutter / 2),
    shape: (50% - gutter / 2, 50% - gutter / 2),
  )

  let indicator-inset-0 = (
    target: (
      position: (0.8, 0.8150312203520691),
      shape: (0, 0),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-0,
    connectors: (
      anchors: (bottom + left, top + left),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-1 = (
    target: (
      position: (1.6, 0.35465473742470827),
      shape: (0, 0),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-1,
    connectors: (
      anchors: (bottom + left, top + left),
      stroke: inset-connector-stroke,
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)

  axes.inset-indicator(..indicator-inset-0)
  axes.inset-indicator(..indicator-inset-1)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.inset(..properties-inset-0, inset-0())
  axes.inset(..properties-inset-1, inset-1())
  axes.abc(..abc-style, 1)
}


#let colorbar-1(lim: (0.0, 1.5)) = {
  let scale = 1 / (lim.at(1) - lim.at(0)) * 100%
  let shift = 50% - (lim.at(0) + lim.at(1)) / 2 * scale

  let transform(point) = {
    let (x, y) = point
    return (0, 100% - (y * scale + shift))
  }


  let label-colormap = (
    position: (410%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        box(
          width: 4cm,
          text(size: 1em, fill: black, [Atomic density $n(x, y)$]),
        ),
      ),
    ),
  )
  let colormap-major-ticks = (
    locs: range(7).map(c => c * 0.25),
    labels: range(7).map(c => c * 0.25).map(c => $#c$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let colormap-minor-ticks = (
    locs: range(7).map(c => c * 0.25 + 0.125),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  std.place(rect(
    width: 100%,
    height: 100%,
    fill: gradient-atomic-density,
    stroke: spine-stroke,
  ))
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..colormap-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..colormap-major-ticks, transform)
  draw.text(..label-colormap)
}


#let grid-0() = {
  let padding = (left: 12.5%, right: 12.0%, top: 2.0%, bottom: 16.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (2.0fr, 0.9fr, 0.1fr),
        rows: (1fr,),
        column-gutter: 4mm,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (2, 0),
          shape: (1, 1),
          colorbar-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 12.01cm, height: 6.7cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
