// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let ylabel-text = [$"Energy"slash #unit[Erec]$]
#let xaxis-minor-tick-locs = range(-3, 4).map(x => x / 2)

#let axes-0(xlim: (-1.55, 1.55), ylim: (-1.5, 26.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111.21%),
    body: place(center + top, text(size: 1em, fill: black, [Position $x slash a$])),
  )
  let label-yaxis = (
    position: (-11.655%, 50.0%),
    body: rotate(-90.0deg, place(center + bottom, text(
      size: 1em,
      fill: black,
      bottom-edge: "descender",
      ylabel-text,
    ))),
  )
  let xaxis-major-ticks = (
    locs: (-2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−2$, $−1$, $0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0),
    labels: ($−5$, $0$, $5$, $10$, $15$, $20$, $25$, $30$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(0, 5).map(y => y * 5 + 2.5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let fill-1 = color.rgb(0.0%, 44.706%, 69.804%, 50.0%)
  let stroke-1 = (
    paint: color.rgb(0.0%, 44.706%, 69.804%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-1 = transform
  let compute-scale-1 = compute-scale
  let offset-transform-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-1,
    stroke: stroke-1,
    transform: transform-1,
    compute-scale: compute-scale-1,
    offset-transform: offset-transform-1,
  )

  let stroke-2 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  let fill-3 = color.rgb(83.529%, 36.863%, 0.0%, 50.0%)
  let stroke-3 = (
    paint: color.rgb(83.529%, 36.863%, 0.0%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-3 = transform
  let compute-scale-3 = compute-scale
  let offset-transform-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-3,
    stroke: stroke-3,
    transform: transform-3,
    compute-scale: compute-scale-3,
    offset-transform: offset-transform-3,
  )

  let stroke-4 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-4 = none
  let line-4 = (
    data: data.at("line-4"),
    stroke: stroke-4,
    marker: marker-4,
    transform: transform,
  )

  let fill-5 = color.rgb(0.0%, 61.961%, 45.098%, 50.0%)
  let stroke-5 = (
    paint: color.rgb(0.0%, 61.961%, 45.098%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-5 = transform
  let compute-scale-5 = compute-scale
  let offset-transform-5 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-5 = (
    data: data.at("collection-5"),
    fill: fill-5,
    stroke: stroke-5,
    transform: transform-5,
    compute-scale: compute-scale-5,
    offset-transform: offset-transform-5,
  )

  let stroke-6 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-6 = none
  let line-6 = (
    data: data.at("line-6"),
    stroke: stroke-6,
    marker: marker-6,
    transform: transform,
  )

  let fill-7 = color.rgb(80.0%, 47.451%, 65.49%, 50.0%)
  let stroke-7 = (
    paint: color.rgb(80.0%, 47.451%, 65.49%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-7 = transform
  let compute-scale-7 = compute-scale
  let offset-transform-7 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-7 = (
    data: data.at("collection-7"),
    fill: fill-7,
    stroke: stroke-7,
    transform: transform-7,
    compute-scale: compute-scale-7,
    offset-transform: offset-transform-7,
  )

  let stroke-8 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-8 = none
  let line-8 = (
    data: data.at("line-8"),
    stroke: stroke-8,
    marker: marker-8,
    transform: transform,
  )

  let text-9 = (
    position: transform((1.48, 4.1)),
    body: place(right + bottom, text(size: 1em, fill: colors(0), [$n = 1$])),
  )

  let text-10 = (
    position: transform((1.48, 10.8)),
    body: place(right + bottom, text(size: 1em, fill: colors(1), [$n = 2$])),
  )

  let text-11 = (
    position: transform((1.48, 15.7)),
    body: place(right + bottom, text(size: 1em, fill: colors(2), [$n = 3$])),
  )

  let text-12 = (
    position: transform((1.48, 19.2)),
    body: place(right + bottom, text(size: 1em, fill: colors(3), [$n = 4$])),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.collection(..collection-1)
  draw.collection(..collection-3)
  draw.collection(..collection-5)
  draw.collection(..collection-7)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-2)
  draw.line(..line-4)
  draw.line(..line-6)
  draw.line(..line-8)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-9)
  draw.text(..text-10)
  draw.text(..text-11)
  draw.text(..text-12)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-1.55, 1.55), ylim: (-0.30000000000000004, 6.3), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 111.21%),
    body: place(center + top, text(size: 1em, fill: black, [Position $x slash a$])),
  )
  let label-yaxis = (
    position: (108.582%, 50.0%),
    body: rotate(-90.0deg, place(center + top, text(size: 1em, fill: black, ylabel-text))),
  )
  let xaxis-major-ticks = (
    locs: (-2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−2$, $−1$, $0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0),
    labels: ($−1$, $0$, $1$, $2$, $3$, $4$, $5$, $6$, $7$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(6).map(y => y + 0.5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-0 = (
    paint: black,
    thickness: linewidth-very-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-0 = none
  let line-0 = (
    data: ((xlim.at(0), 2.161), (xlim.at(1), 2.161)),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let stroke-1 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-1,
    marker: marker-1,
    transform: transform,
  )

  let stroke-2 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  let stroke-3 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-3,
    marker: marker-3,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 7.926%, right: 6.634%, top: 1.389%, bottom: 15.685%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: (1.626%,),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
