// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let axes-0(xlim: (-8.2, 8.2), ylim: (-8.8, 8.8), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: black + 0.6pt),
    right: (bounds: (100.0%, 0.0%), stroke: black + 0.6pt),
    bottom: (bounds: (0.0%, 100.0%), stroke: black + 0.6pt),
    top: (bounds: (0.0%, 100.0%), stroke: black + 0.6pt),
  )

  let label-xaxis = (
    position: (50.0%, 111.21%),
    body: place(center + top, text(size: 1em, fill: black, [Interaction $U slash t$])),
  )
  let label-yaxis = (
    position: (-12.456%, 50.0%),
    body: rotate(-90.0deg, place(center + bottom, text(
      size: 1em,
      fill: black,
      bottom-edge: "descender",
      [Energy $epsilon slash t$],
    ))),
  )
  let xaxis-major-ticks = (
    locs: (-10.0, -8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0, 10.0),
    labels: ($−10$, $−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$, $10$),
    tick-style: (direction: "out", line: (length: 4.0pt, angle: 90deg, stroke: black + 0.6pt)),
    label-style: (pad: 2.0pt, rotation: -0.0deg, text: (size: 1em, fill: black)),
  )
  let xaxis-minor-ticks = (
    locs: (
      -7.5,
      -7.0,
      -6.5,
      -5.5,
      -5.0,
      -4.5,
      -3.5,
      -3.0,
      -2.5,
      -1.5,
      -1.0,
      -0.5,
      0.5,
      1.0,
      1.5,
      2.5,
      3.0,
      3.5,
      4.5,
      5.0,
      5.5,
      6.5,
      7.0,
      7.5,
    ),
    labels: ($$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$, $$),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 90deg, stroke: black + 0.48pt)),
    label-style: (pad: 2.0pt, rotation: -0.0deg, text: (size: 1em, fill: black)),
  )
  let yaxis-major-ticks = (
    locs: (-10.0, -7.5, -5.0, -2.5, 0.0, 2.5, 5.0, 7.5, 10.0),
    labels: ($−10$, $−7.5$, $−5$, $−2.5$, $0$, $2.5$, $5$, $7.5$, $10$),
    tick-style: (direction: "out", line: (length: 4.0pt, angle: 0deg, stroke: black + 0.6pt)),
    label-style: (pad: 2.0pt, rotation: -0.0deg, text: (size: 1em, fill: black)),
  )
  let yaxis-minor-ticks = (
    locs: (
      -9.0,
      -8.5,
      -8.0,
      -7.0,
      -6.5,
      -6.0,
      -5.5,
      -4.5,
      -4.0,
      -3.5,
      -3.0,
      -2.0,
      -1.5,
      -1.0,
      -0.5,
      0.5,
      1.0,
      1.5,
      2.0,
      3.0,
      3.5,
      4.0,
      4.5,
      5.5,
      6.0,
      6.5,
      7.0,
      8.0,
      8.5,
      9.0,
    ),
    labels: (
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
      $$,
    ),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 0deg, stroke: black + 0.48pt)),
    label-style: (pad: 2.0pt, rotation: -0.0deg, text: (size: 1em, fill: black)),
  )

  let stroke-0 = (paint: color.rgb("#0072b2ff"), thickness: 2.0pt, cap: "butt", join: "round", dash: "solid")
  let marker-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let stroke-1 = (paint: color.rgb("#d55e00ff"), thickness: 2.0pt, cap: "butt", join: "round", dash: "solid")
  let marker-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-1,
    marker: marker-1,
    transform: transform,
  )

  let stroke-2 = (paint: color.rgb("#009e73ff"), thickness: 2.0pt, cap: "butt", join: "round", dash: "solid")
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  let stroke-3 = (paint: color.rgb("#cc79a7ff"), thickness: 2.0pt, cap: "butt", join: "round", dash: "solid")
  let marker-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-3,
    marker: marker-3,
    transform: transform,
  )

  let text-4 = (
    position: transform((-7, -8.0)),
    body: place(left + horizon, text(size: 1em, fill: black, bottom-edge: "descender", [$epsilon_1$])),
  )

  let text-5 = (
    position: transform((-7, -5.4)),
    body: place(left + horizon, text(size: 1em, fill: black, bottom-edge: "descender", [$epsilon_2$])),
  )

  let text-6 = (
    position: transform((-7, -0.6)),
    body: place(left + horizon, text(size: 1em, fill: black, bottom-edge: "descender", [$epsilon_3$])),
  )

  let text-7 = (
    position: transform((-7, 1.4)),
    body: place(left + horizon, text(size: 1em, fill: black, bottom-edge: "descender", [$epsilon_4$])),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-4)
  draw.text(..text-5)
  draw.text(..text-6)
  draw.text(..text-7)
}


#let grid-0() = {
  let padding = (left: 15.889%, right: 1.042%, top: 1.389%, bottom: 15.685%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr,),
        rows: (1fr,),
        column-gutter: (),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
      ),
    ),
  )
}


#let figure(width: 10.16cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
