// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let color-long = red
#let color-short = green
#let xaxis-minor-tick-locs = range(-3, 4).map(x => x / 2)
#let yaxis-minor-tick-locs = range(-3, 5).map(y => y * 5)

#let draw-unit-cell(p0, p1, fill: none, stroke: none) = {
  if fill == none { fill = fill-mask }
  if stroke == none { stroke = fill-mask }
  let (x0, y0) = p0
  let (x1, y1) = p1
  let width = x1 - x0
  let height = y1 - y0
  std.place(
    top + left,
    dx: x0,
    dy: y0,
    rect(
      width: width,
      height: height,
      fill: fill,
      stroke: stroke,
    ),
  )
}

#let label-xaxis = (
  position: (50.0%, 119%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [Position $x slash along$]),
  ),
)

#let axes-0(xlim: (-1.55, 1.55), ylim: (-17.8, 21.8), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (-20.155%, 50.0%),
    body: rotate(-90.0deg, place(center + bottom, text(
      size: 1em,
      fill: black,
      bottom-edge: "descender",
      [Potential $V slash #unit[Erecl]$],
    ))),
  )
  let xaxis-major-ticks = (
    locs: (-2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−2$, $−1$, $0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-20.0, -10.0, 0.0, 10.0, 20.0, 30.0),
    labels: ($−20$, $−10$, $0$, $10$, $20$, $30$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: yaxis-minor-tick-locs,
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-0 = (
    paint: color-long,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let stroke-1 = (
    paint: color-short,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-1,
    marker: marker-1,
    transform: transform,
  )

  let stroke-2 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw-unit-cell(transform((-0.5, ylim.at(1))), transform((0.5, ylim.at(0))))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-1.55, 1.55), ylim: (-17.8, 21.8), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let xaxis-major-ticks = (
    locs: (-2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−2$, $−1$, $0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-20.0, -10.0, 0.0, 10.0, 20.0, 30.0),
    labels: ($−20$, $−10$, $0$, $10$, $20$, $30$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: yaxis-minor-tick-locs,
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-0 = (
    paint: color-long,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let stroke-1 = (
    paint: color-long,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (1.85pt, 0.8pt), phase: 0.0pt),
  )
  let marker-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-1,
    marker: marker-1,
    transform: transform,
  )

  let stroke-2 = (
    paint: color-short,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  let stroke-3 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-3,
    marker: marker-3,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw-unit-cell(transform((-0.5, ylim.at(1))), transform((0.5, ylim.at(0))))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let axes-2(xlim: (-1.55, 1.55), ylim: (-17.8, 21.8), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let xaxis-major-ticks = (
    locs: (-2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−2$, $−1$, $0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-20.0, -10.0, 0.0, 10.0, 20.0, 30.0),
    labels: ($−20$, $−10$, $0$, $10$, $20$, $30$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: yaxis-minor-tick-locs,
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-0 = (
    paint: color-long,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let stroke-1 = (
    paint: color-long,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (1.85pt, 0.8pt), phase: 0.0pt),
  )
  let marker-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-1,
    marker: marker-1,
    transform: transform,
  )

  let stroke-2 = (
    paint: color-short,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  let stroke-3 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-3,
    marker: marker-3,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw-unit-cell(transform((-0.5, ylim.at(1))), transform((0.5, ylim.at(0))))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 3)
}


#let grid-0() = {
  let padding = (left: 9.182%, right: 0.641%, top: 2.084%, bottom: 25.028%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr, 1fr),
        rows: (1fr,),
        column-gutter: gutter,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (2, 0),
          shape: (1, 1),
          axes-2(),
        ),
      ),
    ),
  )
}


#let figure(width: 16.51cm, height: 5.08cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
