// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *
#import "@preview/cetz:0.4.2"

#set page(width: 17cm, height: auto, margin: 0.9em)

#let text-box = text-box.with(stroke: none, fill: none)

#let xaxis-label = [Offset $Delta slash t$]
#let xaxis-minor-tick-locs = range(-3, 3).map(x => x * 2 + 1)

#let doublewell-sketch(xscale: 2, yscale: 1.4) = {
  let xmin = -1
  let xmax = 0
  let dx = 0.01
  let xdata = range(int(xmin / dx), int(xmax / dx) + 1).map(x => x * dx)

  let energy-style = (dash: "dotted", thickness: 0.7pt)
  let tunneling-style = (angle: 50deg, width: 0.46 * xscale)
  let arrow-symbol = "triangle"

  let potential(x, vl, vs, phi) = (
    vs * calc.pow(calc.cos(2 * x * calc.pi), 2) - vl * calc.pow(calc.sin((x - phi) * calc.pi), 2)
  )

  let draw-potential(color, phase: 0) = cetz.draw.line(
    ..xdata.map(x => (x * xscale, potential(x, 0.4 * yscale, yscale, phase))),
    stroke: color + linewidth-narrow,
  )

  let draw-single(
    x,
    y,
    radius: 0.16,
    stroke: none,
    color: blue,
  ) = cetz.draw.circle(
    (x * xscale, y),
    radius: radius,
    stroke: stroke,
    fill: gradient.radial(
      white,
      color,
      focal-center: auto,
      center: (40%, 40%),
    ),
  )

  let draw-tunneling(x, angle: 45deg, width: 0.9, name: none) = {
    assert.ne(name, none, message: "The name must not be none!")
    let color = luma(50%)
    cetz.draw.set-style(mark: (symbol: arrow-symbol, fill: color))

    let radius = width / 2 / calc.sin(angle)
    let x0 = x - calc.sin(angle) * radius
    let y0 = (calc.cos(angle) - 1) * radius
    cetz.draw.arc(
      (x0, y0),
      start: 90deg + angle,
      stop: 90deg - angle,
      radius: radius,
      stroke: color,
      name: name,
    )
  }

  // for the correct vertical alignment of the tunneling amplitudes...
  show math.equation: set text(top-edge: "x-height", bottom-edge: "baseline")

  let x-shift = 0.24 // the shift of the atoms from the double-well center
  let y-single = 0.35 * yscale
  let y-delta = -0.16 * yscale
  let y-left = y-single - y-delta
  let y-right = y-single + y-delta

  show: figure-style
  cetz.canvas({
    import cetz.draw: *
    set-style(mark: (scale: 0.7))

    // the static double wells
    draw-potential(black, phase: 0.14)

    // label the on-site energies...
    line((0.04 * xscale, y-left), (-0.85 * xscale, y-left), stroke: energy-style, name: "energy-left")
    line((0.04 * xscale, y-right), (-0.40 * xscale, y-right), stroke: energy-style, name: "energy-right")

    // draw the atoms...
    draw-single(-0.5 - x-shift, y-single - y-delta, color: luma(20%).transparentize(70%))
    draw-single(-0.5 + x-shift, y-single + y-delta, color: luma(20%))

    // draw the tunneling arrows...
    scope({
      translate(y: 0.9 * yscale)
      draw-tunneling(-0.5 * xscale, ..tunneling-style, name: "static-single")
    })

    content((rel: (0, 0.2), to: "static-single.arc-center"), $t$)
    // content((rel: (0, 0.3), to: "static-double.arc-center"), $J = (4t^2) / U$)

    // label the modulation amplitude...
    line(
      (rel: (0.1, 0), to: "energy-right.start"),
      (rel: (0.1, 0), to: "energy-left.start"),
      mark: (end: arrow-symbol, fill: black),
      name: "delta",
    )
    content((rel: (0.06 * xscale, -0.02 * yscale), to: "delta"), $2 Delta$, anchor: "west")
  })
}


#let axes-0(xlim: (-6.3, 6.3), ylim: (-6.6910387833280405, 6.6910387833280405), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111.21%),
    body: place(
      center + top,
      text(size: 1em, fill: black, xaxis-label),
    ),
  )
  let label-yaxis = (
    position: (-14%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, [Energy $epsilon slash t$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    labels: ($−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    labels: ($−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(-3, 3).map(y => y * 2 + 1),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: gradient.linear(..gradient-colors(color-left, (45%, 20%), color-right)),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: gradient.linear(..gradient-colors(color-right, (45%, 20%), color-left)),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let marks = marks.with(outset: 0.3em)
  let basis-states = $marks(ketL, color: #color-left) quad marks(ketR, color: #color-right)$

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(bottom + center, dy: -6%, basis-states)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  std.place(dx: 28%, dy: 3%, doublewell-sketch(xscale: 1.95))
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-6.3, 6.3), ylim: (-0.04251665810767906, 1.042516658107679), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 111.21%),
    body: place(
      center + top,
      text(size: 1em, fill: black, xaxis-label),
    ),
  )
  let label-yaxis = (
    position: (113.875%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        text(size: 1em, fill: black, [Ground-state composition $abs(phy.braket(psi, g))^2$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    labels: ($−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-0.2, 0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2),
    labels: ($−0.2$, $0$, $0.2$, $0.4$, $0.6$, $0.8$, $1$, $1.2$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(0, 5).map(y => y * 0.2 + 0.1),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: color-left,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-right,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 8.655%, right: 9.743%, top: 1.389%, bottom: 15.685%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: gutter,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
