// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let frequency-ylim = (113.5, 125.5)

#let label-yaxis-x0 = -30%

#let label-xaxis = (
  position: (50.0%, 120%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [$y slash#unit[μm]$]),
  ),
)

#let frequency-yaxis-major-ticks = (
  locs: (110.0, 115.0, 120.0, 125.0),
  labels: ($110$, $115$, $120$, $125$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let frequency-yaxis-minor-ticks = (
  locs: (117.5, 122.5),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let resonance-yaxis-major-ticks = (
  locs: (-0.5, 0.0, 0.5, 1.0, 1.5),
  labels: ($−0.5$, $0$, $0.5$, $1$, $1.5$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let resonance-yaxis-minor-ticks = (
  locs: (0.25, 0.75),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let density-yaxis-major-ticks = (
  locs: (-1.0, 0.0, 1.0, 2.0, 3.0),
  labels: ($−1$, $0$, $1$, $2$, $3$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let density-yaxis-minor-ticks = (
  locs: (0.5, 1.5),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let xaxis-major-ticks = (
  locs: (-30.0, 0.0, 30.0),
  labels: ($−30$, $0$, $30$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (-15, 15),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let axes-0(xlim: (-42.0, 42.0), ylim: frequency-ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (label-yaxis-x0, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, [Frequency $f slash #h(0.1em) #unit[kHz]$]),
      ),
    ),
  )

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let gradient-quad-mesh-1 = gradient.linear(white, colors(0))
  let colormap-quad-mesh-1(v, vmin: 0.0, vmax: 1.0) = gradient-quad-mesh-1.sample((v - vmin) / (vmax - vmin) * 100%)
  let quad-mesh-1 = (
    data: data.at("quad-mesh-1"),
    colormap: colormap-quad-mesh-1,
    transform: transform,
  )

  let yaxis-major-ticks = frequency-yaxis-major-ticks
  let yaxis-minor-ticks = frequency-yaxis-minor-ticks

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.quad-mesh(..quad-mesh-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-42.0, 42.0), ylim: frequency-ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let yaxis-major-ticks = frequency-yaxis-major-ticks
  let yaxis-minor-ticks = frequency-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let gradient-quad-mesh-1 = gradient.linear(white, colors(1))
  let colormap-quad-mesh-1(v, vmin: 0.0, vmax: 1.0) = gradient-quad-mesh-1.sample((v - vmin) / (vmax - vmin) * 100%)
  let quad-mesh-1 = (
    data: data.at("quad-mesh-1"),
    colormap: colormap-quad-mesh-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.quad-mesh(..quad-mesh-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 2)
}


#let axes-2(xlim: (-42.0, 42.0), ylim: frequency-ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let yaxis-major-ticks = frequency-yaxis-major-ticks
  let yaxis-minor-ticks = frequency-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let gradient-quad-mesh-1 = gradient.linear(white, colors(2))
  let colormap-quad-mesh-1(v, vmin: 0.0, vmax: 1.0) = gradient-quad-mesh-1.sample((v - vmin) / (vmax - vmin) * 100%)
  let quad-mesh-1 = (
    data: data.at("quad-mesh-1"),
    colormap: colormap-quad-mesh-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.quad-mesh(..quad-mesh-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 3)
}


#let axes-3(xlim: (-42.0, 42.0), ylim: frequency-ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")

  let yaxis-major-ticks = frequency-yaxis-major-ticks
  let yaxis-minor-ticks = frequency-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let gradient-quad-mesh-1 = gradient.linear(white, colors(3))
  let colormap-quad-mesh-1(v, vmin: 0.0, vmax: 1.0) = gradient-quad-mesh-1.sample((v - vmin) / (vmax - vmin) * 100%)
  let quad-mesh-1 = (
    data: data.at("quad-mesh-1"),
    colormap: colormap-quad-mesh-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.quad-mesh(..quad-mesh-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 4)
}


#let axes-4(xlim: (-42.0, 42.0), ylim: (-0.04, 1.04), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-4.json")

  let label-yaxis = (
    position: (label-yaxis-x0, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, [Resonance $R$]),
      ),
    ),
  )

  let yaxis-major-ticks = resonance-yaxis-major-ticks
  let yaxis-minor-ticks = resonance-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 5)
}


#let axes-5(xlim: (-42.0, 42.0), ylim: (-0.04, 1.04), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-5.json")

  let yaxis-major-ticks = resonance-yaxis-major-ticks
  let yaxis-minor-ticks = resonance-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 6)
}


#let axes-6(xlim: (-42.0, 42.0), ylim: (-0.04, 1.04), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-6.json")

  let yaxis-major-ticks = resonance-yaxis-major-ticks
  let yaxis-minor-ticks = resonance-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 7)
}


#let axes-7(xlim: (-42.0, 42.0), ylim: (-0.04, 1.04), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-7.json")

  let yaxis-major-ticks = resonance-yaxis-major-ticks
  let yaxis-minor-ticks = resonance-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 8)
}


#let axes-8(xlim: (-42.0, 42.0), ylim: (-0.08, 2.08), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-8.json")

  let label-yaxis = (
    position: (label-yaxis-x0, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, [Atomic density $n slash#unit[μm]$]),
      ),
    ),
  )

  let yaxis-major-ticks = density-yaxis-major-ticks
  let yaxis-minor-ticks = density-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-yaxis)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 9)
}


#let axes-9(xlim: (-42.0, 42.0), ylim: (-0.08, 2.08), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-9.json")

  let yaxis-major-ticks = density-yaxis-major-ticks
  let yaxis-minor-ticks = density-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 10)
}


#let axes-10(xlim: (-42.0, 42.0), ylim: (-0.08, 2.08), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-10.json")

  let yaxis-major-ticks = density-yaxis-major-ticks
  let yaxis-minor-ticks = density-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 11)
}


#let axes-11(xlim: (-42.0, 42.0), ylim: (-0.08, 2.08), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-11.json")

  let yaxis-major-ticks = density-yaxis-major-ticks
  let yaxis-minor-ticks = density-yaxis-minor-ticks

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 12)
}


#let grid-0() = {
  let padding = (left: 8.5%, right: 0.9%, top: 2%, bottom: 9%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr, 1fr, 1fr),
        rows: (1fr, 1fr, 1fr),
        column-gutter: gutter-narrow,
        row-gutter: gutter-narrow,
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (2, 0),
          shape: (1, 1),
          axes-2(),
        ),
        axes.cell(
          position: (3, 0),
          shape: (1, 1),
          axes-3(),
        ),
        axes.cell(
          position: (0, 1),
          shape: (1, 1),
          axes-4(),
        ),
        axes.cell(
          position: (1, 1),
          shape: (1, 1),
          axes-5(),
        ),
        axes.cell(
          position: (2, 1),
          shape: (1, 1),
          axes-6(),
        ),
        axes.cell(
          position: (3, 1),
          shape: (1, 1),
          axes-7(),
        ),
        axes.cell(
          position: (0, 2),
          shape: (1, 1),
          axes-8(),
        ),
        axes.cell(
          position: (1, 2),
          shape: (1, 1),
          axes-9(),
        ),
        axes.cell(
          position: (2, 2),
          shape: (1, 1),
          axes-10(),
        ),
        axes.cell(
          position: (3, 2),
          shape: (1, 1),
          axes-11(),
        ),
      ),
    ),
  )
}


#let figure(width: 16cm, height: 12.1cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
