// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let ylim = (-3.0, 73.0)

#let label-xaxis-y0 = 110%

#let yaxis-major-ticks = (
  locs: (-10.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0),
  labels: ($−10$, $0$, $10$, $20$, $30$, $40$, $50$, $60$, $70$, $80$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: range(7).map(y => y * 10 + 5),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let axes-0(xlim: (-1.55, 1.55), ylim: ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, label-xaxis-y0),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Position $x slash a$]),
    ),
  )
  let label-yaxis = (
    position: (-12%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(
          size: 1em,
          fill: black,
          bottom-edge: "descender",
          [Band energy $epsilon_n slash #unit[Erec]$],
        ),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−2$, $−1$, $0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (-1.5, -0.5, 0.5, 1.5),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )

  let fill-collection-1 = colors(0).transparentize(50%)
  let stroke-collection-1 = (
    paint: colors(0).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let stroke-line-3 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let fill-collection-4 = color.rgb(50.0%, 50.0%, 50.0%, 50.0%).darken(40%)
  let stroke-collection-4 = (
    paint: color.rgb(50.0%, 50.0%, 50.0%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-4 = transform
  let compute-scale-collection-4 = compute-scale
  let offset-transform-collection-4 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-4 = (
    data: data.at("collection-4"),
    fill: fill-collection-4,
    stroke: stroke-collection-4,
    transform: transform-collection-4,
    compute-scale: compute-scale-collection-4,
    offset-transform: offset-transform-collection-4,
  )

  let fill-collection-5 = colors(1).transparentize(50%)
  let stroke-collection-5 = (
    paint: colors(1).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-5 = transform
  let compute-scale-collection-5 = compute-scale
  let offset-transform-collection-5 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-5 = (
    data: data.at("collection-5"),
    fill: fill-collection-5,
    stroke: stroke-collection-5,
    transform: transform-collection-5,
    compute-scale: compute-scale-collection-5,
    offset-transform: offset-transform-collection-5,
  )

  let stroke-line-6 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-6 = none
  let line-6 = (
    data: data.at("line-6"),
    stroke: stroke-line-6,
    marker: marker-line-6,
    transform: transform,
  )

  let fill-collection-9 = colors(2).transparentize(50%)
  let stroke-collection-9 = (
    paint: colors(2).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-9 = transform
  let compute-scale-collection-9 = compute-scale
  let offset-transform-collection-9 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-9 = (
    data: data.at("collection-9"),
    fill: fill-collection-9,
    stroke: stroke-collection-9,
    transform: transform-collection-9,
    compute-scale: compute-scale-collection-9,
    offset-transform: offset-transform-collection-9,
  )

  let stroke-line-10 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-10 = none
  let line-10 = (
    data: data.at("line-10"),
    stroke: stroke-line-10,
    marker: marker-line-10,
    transform: transform,
  )

  let fill-collection-13 = colors(3).transparentize(50%)
  let stroke-collection-13 = (
    paint: colors(3).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-13 = transform
  let compute-scale-collection-13 = compute-scale
  let offset-transform-collection-13 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-13 = (
    data: data.at("collection-13"),
    fill: fill-collection-13,
    stroke: stroke-collection-13,
    transform: transform-collection-13,
    compute-scale: compute-scale-collection-13,
    offset-transform: offset-transform-collection-13,
  )

  let stroke-line-14 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-14 = none
  let line-14 = (
    data: data.at("line-14"),
    stroke: stroke-line-14,
    marker: marker-line-14,
    transform: transform,
  )

  let fill-collection-17 = colors(4).transparentize(50%)
  let stroke-collection-17 = (
    paint: colors(4).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-17 = transform
  let compute-scale-collection-17 = compute-scale
  let offset-transform-collection-17 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-17 = (
    data: data.at("collection-17"),
    fill: fill-collection-17,
    stroke: stroke-collection-17,
    transform: transform-collection-17,
    compute-scale: compute-scale-collection-17,
    offset-transform: offset-transform-collection-17,
  )

  let stroke-line-18 = (
    paint: colors(4),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-18 = none
  let line-18 = (
    data: data.at("line-18"),
    stroke: stroke-line-18,
    marker: marker-line-18,
    transform: transform,
  )

  let fill-collection-21 = colors(5).transparentize(50%)
  let stroke-collection-21 = (
    paint: colors(5).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-21 = transform
  let compute-scale-collection-21 = compute-scale
  let offset-transform-collection-21 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-21 = (
    data: data.at("collection-21"),
    fill: fill-collection-21,
    stroke: stroke-collection-21,
    transform: transform-collection-21,
    compute-scale: compute-scale-collection-21,
    offset-transform: offset-transform-collection-21,
  )

  let stroke-line-22 = (
    paint: colors(5),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-22 = none
  let line-22 = (
    data: data.at("line-22"),
    stroke: stroke-line-22,
    marker: marker-line-22,
    transform: transform,
  )

  let text-25 = (
    position: transform((1.48, 10)),
    body: place(
      right + bottom,
      text(size: 1em, fill: colors(0), [$n = 1$]),
    ),
  )

  let text-26 = (
    position: transform((1.48, 24)),
    body: place(
      right + bottom,
      text(size: 1em, fill: colors(1), [$n = 2$]),
    ),
  )

  let text-27 = (
    position: transform((1.48, 38)),
    body: place(
      right + bottom,
      text(size: 1em, fill: colors(2), [$n = 3$]),
    ),
  )

  let text-28 = (
    position: transform((1.48, 48)),
    body: place(
      right + bottom,
      text(size: 1em, fill: colors(3), [$n = 4$]),
    ),
  )

  let text-29 = (
    position: transform((1.48, 60)),
    body: place(
      right + bottom,
      text(size: 1em, fill: colors(4), [$n = 5$]),
    ),
  )

  let text-30 = (
    position: transform((1.48, 65)),
    body: place(
      right + bottom,
      text(size: 1em, fill: colors(5), [$n = 6$]),
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.collection(..collection-1)
  draw.collection(..collection-4)
  draw.collection(..collection-5)
  draw.collection(..collection-9)
  draw.collection(..collection-13)
  draw.collection(..collection-17)
  draw.collection(..collection-21)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-2)
  draw.line(..line-3)
  draw.line(..line-6)
  draw.line(..line-10)
  draw.line(..line-14)
  draw.line(..line-18)
  draw.line(..line-22)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-25)
  draw.text(..text-26)
  draw.text(..text-27)
  draw.text(..text-28)
  draw.text(..text-29)
  draw.text(..text-30)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-2.0, 67.0), ylim: ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, label-xaxis-y0),
    body: place(
      center + top,
      text(
        size: 1em,
        fill: black,
        [Lattice depth $V0 slash #unit[Erec]$],
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-20.0, 0.0, 20.0, 40.0, 60.0, 80.0),
    labels: ($−20$, $0$, $20$, $40$, $60$, $80$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (10, 30, 50),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )

  let fill-collection-1 = colors(0).transparentize(50%)
  let stroke-collection-1 = (
    paint: colors(0).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: color.luma(50.0%),
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let fill-collection-3 = colors(1).transparentize(50%)
  let stroke-collection-3 = (
    paint: colors(1).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  let fill-collection-5 = colors(2).transparentize(50%)
  let stroke-collection-5 = (
    paint: colors(2).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-5 = transform
  let compute-scale-collection-5 = compute-scale
  let offset-transform-collection-5 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-5 = (
    data: data.at("collection-5"),
    fill: fill-collection-5,
    stroke: stroke-collection-5,
    transform: transform-collection-5,
    compute-scale: compute-scale-collection-5,
    offset-transform: offset-transform-collection-5,
  )

  let fill-collection-7 = colors(3).transparentize(50%)
  let stroke-collection-7 = (
    paint: colors(3).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-7 = transform
  let compute-scale-collection-7 = compute-scale
  let offset-transform-collection-7 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-7 = (
    data: data.at("collection-7"),
    fill: fill-collection-7,
    stroke: stroke-collection-7,
    transform: transform-collection-7,
    compute-scale: compute-scale-collection-7,
    offset-transform: offset-transform-collection-7,
  )

  let fill-collection-9 = colors(4).transparentize(50%)
  let stroke-collection-9 = (
    paint: colors(4).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-9 = transform
  let compute-scale-collection-9 = compute-scale
  let offset-transform-collection-9 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-9 = (
    data: data.at("collection-9"),
    fill: fill-collection-9,
    stroke: stroke-collection-9,
    transform: transform-collection-9,
    compute-scale: compute-scale-collection-9,
    offset-transform: offset-transform-collection-9,
  )

  let fill-collection-11 = colors(5).transparentize(50%)
  let stroke-collection-11 = (
    paint: colors(5).transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-11 = transform
  let compute-scale-collection-11 = compute-scale
  let offset-transform-collection-11 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-11 = (
    data: data.at("collection-11"),
    fill: fill-collection-11,
    stroke: stroke-collection-11,
    transform: transform-collection-11,
    compute-scale: compute-scale-collection-11,
    offset-transform: offset-transform-collection-11,
  )

  let stroke-line-13 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-13 = none
  let line-13 = (
    data: ((60, ylim.at(0)), (60, ylim.at(1))),
    stroke: stroke-line-13,
    marker: marker-line-13,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.collection(..collection-1)
  draw.collection(..collection-3)
  draw.collection(..collection-5)
  draw.collection(..collection-7)
  draw.collection(..collection-9)
  draw.collection(..collection-11)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-2)
  draw.line(..line-13)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 7%, right: 0.9%, top: 1.6%, bottom: 13%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: 3mm,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 14.52cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
