// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

// use a slightly smaller transparency for the other bands...
#let transparency = 80%
#let color-n2 = colors(1).transparentize(transparency)
#let color-n5 = colors(4).transparentize(transparency)
#let color-n6 = colors(5).transparentize(transparency)

// this is the transparency for the bands 3 and 4...
#let transparency = 90%

#let yaxis-major-ticks = (
  locs: (50.0, 100.0, 150.0, 200.0, 250.0, 300.0, 350.0, 400.0, 450.0, 500.0),
  labels: ($50$, $100$, $150$, $200$, $250$, $300$, $350$, $400$, $450$, $500$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: range(7).map(y => y * 50 + 125),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let axes-0(xlim: (9.75, 22.25), ylim: (95.0, 455.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111%),
    body: place(
      center + top,
      text(
        size: 1em,
        fill: black,
        [Lattice depth $Vx532 slash #unit[Erec]$],
      ),
    ),
  )
  let label-yaxis = (
    position: (-14.104%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Transition frequency $fnm(1, n) slash#unit[kHz]$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: range(4).map(x => x * 4 + 10),
    labels: range(4).map(x => x * 4 + 10).map(x => $#x$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (12, 16, 20),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: color.luma(20.0%),
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-0 = none
  let line-0 = (
    data: ylim.map(y => (18, y)),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-n2,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-n2,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let fill-collection-3 = color-n2.transparentize(50%)
  let stroke-collection-3 = (
    paint: color-n2.transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  let colors-n3 = (colors(2),) * 3 + (colors(2).transparentize(transparency),) * 5
  let gradient-n3 = gradient.linear(..colors-n3)
  let gradient-n3-alpha = gradient.linear(
    ..colors-n3.map(c => c.transparentize(50%)),
  )
  let stroke-line-4 = (
    paint: gradient-n3,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-4 = none
  let line-4 = (
    data: data.at("line-4"),
    stroke: stroke-line-4,
    marker: marker-line-4,
    transform: transform,
  )

  let stroke-line-5 = (
    paint: gradient-n3,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-5 = none
  let line-5 = (
    data: data.at("line-5"),
    stroke: stroke-line-5,
    marker: marker-line-5,
    transform: transform,
  )

  let fill-collection-6 = gradient-n3-alpha
  let stroke-collection-6 = (
    paint: gradient-n3-alpha,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-6 = transform
  let compute-scale-collection-6 = compute-scale
  let offset-transform-collection-6 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-6 = (
    data: data.at("collection-6"),
    fill: fill-collection-6,
    stroke: stroke-collection-6,
    transform: transform-collection-6,
    compute-scale: compute-scale-collection-6,
    offset-transform: offset-transform-collection-6,
  )

  let colors-n4 = (colors(3).transparentize(transparency),) * 3 + (colors(3),) * 5
  let gradient-n4 = gradient.linear(..colors-n4)
  let gradient-n4-alpha = gradient.linear(
    ..colors-n4.map(c => c.transparentize(50%)),
  )
  let stroke-line-7 = (
    paint: gradient-n4,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-7 = none
  let line-7 = (
    data: data.at("line-7"),
    stroke: stroke-line-7,
    marker: marker-line-7,
    transform: transform,
  )

  let stroke-line-8 = (
    paint: gradient-n4,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-8 = none
  let line-8 = (
    data: data.at("line-8"),
    stroke: stroke-line-8,
    marker: marker-line-8,
    transform: transform,
  )

  let fill-collection-9 = gradient-n4-alpha
  let stroke-collection-9 = (
    paint: gradient-n4-alpha,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-9 = transform
  let compute-scale-collection-9 = compute-scale
  let offset-transform-collection-9 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-9 = (
    data: data.at("collection-9"),
    fill: fill-collection-9,
    stroke: stroke-collection-9,
    transform: transform-collection-9,
    compute-scale: compute-scale-collection-9,
    offset-transform: offset-transform-collection-9,
  )

  let stroke-line-10 = (
    paint: color-n5,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-10 = none
  let line-10 = (
    data: data.at("line-10"),
    stroke: stroke-line-10,
    marker: marker-line-10,
    transform: transform,
  )

  let stroke-line-11 = (
    paint: color-n5,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-11 = none
  let line-11 = (
    data: data.at("line-11"),
    stroke: stroke-line-11,
    marker: marker-line-11,
    transform: transform,
  )

  let fill-collection-12 = color-n5.transparentize(50%)
  let stroke-collection-12 = (
    paint: color-n5.transparentize(50%),
    thickness: 0.6pt,
    dash: "solid",
  )
  let transform-collection-12 = transform
  let compute-scale-collection-12 = compute-scale
  let offset-transform-collection-12 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-12 = (
    data: data.at("collection-12"),
    fill: fill-collection-12,
    stroke: stroke-collection-12,
    transform: transform-collection-12,
    compute-scale: compute-scale-collection-12,
    offset-transform: offset-transform-collection-12,
  )

  let stroke-line-13 = (
    paint: color-n6,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-13 = none
  let line-13 = (
    data: data.at("line-13"),
    stroke: stroke-line-13,
    marker: marker-line-13,
    transform: transform,
  )

  let stroke-line-14 = (
    paint: color-n6,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-14 = none
  let line-14 = (
    data: data.at("line-14"),
    stroke: stroke-line-14,
    marker: marker-line-14,
    transform: transform,
  )

  let fill-collection-15 = color-n6.transparentize(50%)
  let stroke-collection-15 = (
    paint: color-n6.transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-15 = transform
  let compute-scale-collection-15 = compute-scale
  let offset-transform-collection-15 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-15 = (
    data: data.at("collection-15"),
    fill: fill-collection-15,
    stroke: stroke-collection-15,
    transform: transform-collection-15,
    compute-scale: compute-scale-collection-15,
    offset-transform: offset-transform-collection-15,
  )

  let label-band(label, y) = (
    position: transform((21.8, y)),
    body: place(
      right + bottom,
      text-box(text(size: 1em, fill: black, label)),
    ),
  )

  let labels = (
    label-band($n = 2$, 152),
    label-band($n = 3$, 242),
    label-band($n = 4$, 289),
    label-band($n = 5$, 360),
    label-band($n = 6$, 400),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.collection(..collection-3)
  draw.collection(..collection-6)
  draw.collection(..collection-9)
  draw.collection(..collection-12)
  draw.collection(..collection-15)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-4)
  draw.line(..line-5)
  draw.line(..line-7)
  draw.line(..line-8)
  draw.line(..line-10)
  draw.line(..line-11)
  draw.line(..line-13)
  draw.line(..line-14)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  for label in labels { draw.text(..label) }
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (49.0, 81.0), ylim: (95.0, 455.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 111%),
    body: place(
      center + top,
      text(
        size: 1em,
        fill: black,
        [Lattice depth $Vx1064 slash #unit[Erec]$],
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (40.0, 50.0, 60.0, 70.0, 80.0, 90.0),
    labels: ($40$, $50$, $60$, $70$, $80$, $90$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (55, 65, 75),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: color.luma(20.0%),
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-0 = none
  let line-0 = (
    data: ylim.map(y => (60, y)),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-n2,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-n2,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let fill-collection-3 = color-n2.transparentize(50%)
  let stroke-collection-3 = (
    paint: color-n2.transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  let colors-n3 = (colors(2),) * 7 + (colors(2).transparentize(transparency),) * 5
  let gradient-n3 = gradient.linear(..colors-n3)
  let gradient-n3-alpha = gradient.linear(
    ..colors-n3.map(c => c.transparentize(50%)),
  )
  let stroke-line-4 = (
    paint: gradient-n3,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-4 = none
  let line-4 = (
    data: data.at("line-4"),
    stroke: stroke-line-4,
    marker: marker-line-4,
    transform: transform,
  )

  let stroke-line-5 = (
    paint: gradient-n3,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-5 = none
  let line-5 = (
    data: data.at("line-5"),
    stroke: stroke-line-5,
    marker: marker-line-5,
    transform: transform,
  )

  let fill-collection-6 = gradient-n3-alpha
  let stroke-collection-6 = (
    paint: gradient-n3-alpha,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-6 = transform
  let compute-scale-collection-6 = compute-scale
  let offset-transform-collection-6 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-6 = (
    data: data.at("collection-6"),
    fill: fill-collection-6,
    stroke: stroke-collection-6,
    transform: transform-collection-6,
    compute-scale: compute-scale-collection-6,
    offset-transform: offset-transform-collection-6,
  )

  let colors-n4 = (colors(3).transparentize(transparency),) * 7 + (colors(3),) * 5
  let gradient-n4 = gradient.linear(..colors-n4)
  let gradient-n4-alpha = gradient.linear(
    ..colors-n4.map(c => c.transparentize(50%)),
  )
  let stroke-line-7 = (
    paint: gradient-n4,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-7 = none
  let line-7 = (
    data: data.at("line-7"),
    stroke: stroke-line-7,
    marker: marker-line-7,
    transform: transform,
  )

  let stroke-line-8 = (
    paint: gradient-n4,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-8 = none
  let line-8 = (
    data: data.at("line-8"),
    stroke: stroke-line-8,
    marker: marker-line-8,
    transform: transform,
  )

  let fill-collection-9 = gradient-n4-alpha
  let stroke-collection-9 = (
    paint: gradient-n4-alpha,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-9 = transform
  let compute-scale-collection-9 = compute-scale
  let offset-transform-collection-9 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-9 = (
    data: data.at("collection-9"),
    fill: fill-collection-9,
    stroke: stroke-collection-9,
    transform: transform-collection-9,
    compute-scale: compute-scale-collection-9,
    offset-transform: offset-transform-collection-9,
  )

  let stroke-line-10 = (
    paint: color-n5,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-10 = none
  let line-10 = (
    data: data.at("line-10"),
    stroke: stroke-line-10,
    marker: marker-line-10,
    transform: transform,
  )

  let stroke-line-11 = (
    paint: color-n5,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-11 = none
  let line-11 = (
    data: data.at("line-11"),
    stroke: stroke-line-11,
    marker: marker-line-11,
    transform: transform,
  )

  let fill-collection-12 = color-n5.transparentize(50%)
  let stroke-collection-12 = (
    paint: color-n5.transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-12 = transform
  let compute-scale-collection-12 = compute-scale
  let offset-transform-collection-12 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-12 = (
    data: data.at("collection-12"),
    fill: fill-collection-12,
    stroke: stroke-collection-12,
    transform: transform-collection-12,
    compute-scale: compute-scale-collection-12,
    offset-transform: offset-transform-collection-12,
  )

  let stroke-line-13 = (
    paint: color-n6,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-13 = none
  let line-13 = (
    data: data.at("line-13"),
    stroke: stroke-line-13,
    marker: marker-line-13,
    transform: transform,
  )

  let stroke-line-14 = (
    paint: color-n6,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-14 = none
  let line-14 = (
    data: data.at("line-14"),
    stroke: stroke-line-14,
    marker: marker-line-14,
    transform: transform,
  )

  let fill-collection-15 = color-n6.transparentize(50%)
  let stroke-collection-15 = (
    paint: color-n6.transparentize(50%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-15 = transform
  let compute-scale-collection-15 = compute-scale
  let offset-transform-collection-15 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-15 = (
    data: data.at("collection-15"),
    fill: fill-collection-15,
    stroke: stroke-collection-15,
    transform: transform-collection-15,
    compute-scale: compute-scale-collection-15,
    offset-transform: offset-transform-collection-15,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.collection(..collection-3)
  draw.collection(..collection-6)
  draw.collection(..collection-9)
  draw.collection(..collection-12)
  draw.collection(..collection-15)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-4)
  draw.line(..line-5)
  draw.line(..line-7)
  draw.line(..line-8)
  draw.line(..line-10)
  draw.line(..line-11)
  draw.line(..line-13)
  draw.line(..line-14)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 9.218%, right: 0.695%, top: 2.076%, bottom: 15.404%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: gutter,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 14.26cm, height: 7.6cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
