// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let label-xaxis = (
  position: (50.0%, 110%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [Position $x slash#unit[μm]$]),
  ),
)

#let label-yaxis-text = text(
  size: 1em,
  fill: black,
  bottom-edge: "descender",
  [Modulation frequency $fmod slash#unit[kHz]$],
)

#let xaxis-major-ticks = (
  locs: (-60.0, -40.0, -20.0, 0.0, 20.0, 40.0, 60.0),
  labels: ($−60$, $−40$, $−20$, $0$, $20$, $40$, $60$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (-50, -30, -10, 10, 30),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let axes-0(xlim: (-47.80645161290323, 47.80645161290323), ylim: (110.0, 120.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (-20.438%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        label-yaxis-text,
      ),
    ),
  )
  let yaxis-major-ticks = (
    locs: (108.5, 110.5, 112.5, 114.5, 116.5, 118.5, 120.5),
    labels: ($108.5$, $110.5$, $112.5$, $114.5$, $116.5$, $118.5$, $120.5$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (109.5, 111.5, 113.5, 115.5, 117.5, 119.5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let colormap-quad-mesh-0(v, vmin: 0.0, vmax: 1.45) = gradient-modulation-resonance.sample(
    (v - vmin) / (vmax - vmin) * 100%,
  )
  let quad-mesh-0 = (
    data: data.at("quad-mesh-0"),
    colormap: colormap-quad-mesh-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: black,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.quad-mesh(..quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-47.80645161290323, 47.80645161290323), ylim: (68.5, 76.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-yaxis = (
    position: (112.318%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        label-yaxis-text,
      ),
    ),
  )
  let yaxis-major-ticks = (
    locs: (69.0, 71.0, 73.0, 75.0, 77.0),
    labels: ($69$, $71$, $73$, $75$, $77$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (70, 72, 74, 76),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let colormap-quad-mesh-0(v, vmin: 0.0, vmax: 1.45) = gradient-modulation-resonance.sample(
    (v - vmin) / (vmax - vmin) * 100%,
  )
  let quad-mesh-0 = (
    data: data.at("quad-mesh-0"),
    colormap: colormap-quad-mesh-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: black,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.quad-mesh(..quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 11%, right: 8%, top: 1.4%, bottom: 14%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: (1.717%,),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.65cm, height: 7.36cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
