// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let yaxis-minor-tick-locs = range(-2, 5).map(y => y * 5 + 2.5)

#let draw-unit-cell(p0, p1, fill: black.transparentize(80%), stroke: none) = {
  let (x0, y0) = p0
  let (x1, y1) = p1
  let width = x1 - x0
  let height = y1 - y0
  std.place(
    top + left,
    dx: x0,
    dy: y0,
    rect(
      width: width,
      height: height,
      fill: fill,
      stroke: stroke,
    ),
  )
}

#let axes-0(xlim: (-1.05, 1.05), ylim: (-10.5, 21.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111.347%),
    body: place(center + top, text(size: 1em, fill: black, [Quasimomentum $q slash klong$])),
  )
  let label-yaxis = (
    position: (-14.257%, 50.0%),
    body: rotate(-90.0deg, place(center + bottom, text(
      size: 1em,
      fill: black,
      bottom-edge: "descender",
      [$"Energy"slash #unit[Erec]$],
    ))),
  )
  let xaxis-major-ticks = (
    locs: (-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5),
    labels: ($−1.5$, $−1$, $−0.5$, $0$, $0.5$, $1$, $1.5$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(-3, 4).map(x => x / 4),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 25.0),
    labels: ($−15$, $−10$, $−5$, $0$, $5$, $10$, $15$, $20$, $25$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: yaxis-minor-tick-locs,
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-0 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let stroke-1 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-1,
    marker: marker-1,
    transform: transform,
  )

  let stroke-2 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  let stroke-3 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-3,
    marker: marker-3,
    transform: transform,
  )

  let text-4 = (
    position: transform((1.0, -4.0)),
    body: place(right + bottom, text(size: 1em, fill: colors(0), [$n = 1$])),
  )

  let text-5 = (
    position: transform((1.0, 0.2)),
    body: place(right + bottom, text(size: 1em, fill: colors(1), [$n = 2$])),
  )

  let text-6 = (
    position: transform((1.0, 8.0)),
    body: place(right + bottom, text(size: 1em, fill: colors(2), [$n = 3$])),
  )

  let text-7 = (
    position: transform((1.0, 15.7)),
    body: place(right + bottom, text(size: 1em, fill: colors(3), [$n = 4$])),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-4)
  draw.text(..text-5)
  draw.text(..text-6)
  draw.text(..text-7)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-1.6, 1.6), ylim: (-10.5, 21.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 111.347%),
    body: place(center + top, text(size: 1em, fill: black, [Position $x slash along$])),
  )
  let xaxis-major-ticks = (
    locs: (-2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−2$, $−1$, $0$, $1$, $2$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(-3, 4).map(x => x / 2),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 25.0),
    labels: ($−15$, $−10$, $−5$, $0$, $5$, $10$, $15$, $20$, $25$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: yaxis-minor-tick-locs,
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-0,
    marker: marker-0,
    transform: transform,
  )

  let fill-1 = color.rgb(80.0%, 47.451%, 65.49%, 50.0%)
  let stroke-1 = (
    paint: color.rgb(80.0%, 47.451%, 65.49%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-1 = transform
  let compute-scale-1 = compute-scale
  let offset-transform-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-1,
    stroke: stroke-1,
    transform: transform-1,
    compute-scale: compute-scale-1,
    offset-transform: offset-transform-1,
  )

  let stroke-2 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-2,
    marker: marker-2,
    transform: transform,
  )

  let stroke-3 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-3,
    marker: marker-3,
    transform: transform,
  )

  let fill-4 = color.rgb(0.0%, 61.961%, 45.098%, 50.0%)
  let stroke-4 = (
    paint: color.rgb(0.0%, 61.961%, 45.098%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-4 = transform
  let compute-scale-4 = compute-scale
  let offset-transform-4 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-4 = (
    data: data.at("collection-4"),
    fill: fill-4,
    stroke: stroke-4,
    transform: transform-4,
    compute-scale: compute-scale-4,
    offset-transform: offset-transform-4,
  )

  let stroke-5 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-5 = none
  let line-5 = (
    data: data.at("line-5"),
    stroke: stroke-5,
    marker: marker-5,
    transform: transform,
  )

  let stroke-6 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-6 = none
  let line-6 = (
    data: data.at("line-6"),
    stroke: stroke-6,
    marker: marker-6,
    transform: transform,
  )

  let fill-7 = color.rgb(83.529%, 36.863%, 0.0%, 50.0%)
  let stroke-7 = (
    paint: color.rgb(83.529%, 36.863%, 0.0%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-7 = transform
  let compute-scale-7 = compute-scale
  let offset-transform-7 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-7 = (
    data: data.at("collection-7"),
    fill: fill-7,
    stroke: stroke-7,
    transform: transform-7,
    compute-scale: compute-scale-7,
    offset-transform: offset-transform-7,
  )

  let stroke-8 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-8 = none
  let line-8 = (
    data: data.at("line-8"),
    stroke: stroke-8,
    marker: marker-8,
    transform: transform,
  )

  let stroke-9 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-9 = none
  let line-9 = (
    data: data.at("line-9"),
    stroke: stroke-9,
    marker: marker-9,
    transform: transform,
  )

  let fill-10 = color.rgb(0.0%, 44.706%, 69.804%, 50.0%)
  let stroke-10 = (
    paint: color.rgb(0.0%, 44.706%, 69.804%, 50.0%),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-10 = transform
  let compute-scale-10 = compute-scale
  let offset-transform-10 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-10 = (
    data: data.at("collection-10"),
    fill: fill-10,
    stroke: stroke-10,
    transform: transform-10,
    compute-scale: compute-scale-10,
    offset-transform: offset-transform-10,
  )

  let stroke-11 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-11 = none
  let line-11 = (
    data: data.at("line-11"),
    stroke: stroke-11,
    marker: marker-11,
    transform: transform,
  )

  let stroke-12 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-12 = none
  let line-12 = (
    data: data.at("line-12"),
    stroke: stroke-12,
    marker: marker-12,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw-unit-cell(transform((-0.5, ylim.at(1))), transform((0.5, ylim.at(0))))
  draw.collection(..collection-1)
  draw.collection(..collection-4)
  draw.collection(..collection-7)
  draw.collection(..collection-10)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-2)
  draw.line(..line-3)
  draw.line(..line-5)
  draw.line(..line-6)
  draw.line(..line-8)
  draw.line(..line-9)
  draw.line(..line-11)
  draw.line(..line-12)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 9.28%, right: 0.695%, top: 1.389%, bottom: 16.685%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: (2.571%,),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
