// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let colors = band-colors

#let yaxis-major-ticks = (
  locs: (-300.0, -200.0, -100.0, 0.0, 100.0, 200.0, 300.0),
  labels: ($−300$, $−200$, $−100$, $0$, $100$, $200$, $300$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: range(5).map(y => y * 100 - 250),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let axes-0(xlim: (-1.16, 1.16), ylim: (-285.0, 245.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111%),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Position $x slash ax532$]),
    ),
  )
  let label-yaxis = (
    position: (-19%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(
          size: 1em,
          fill: black,
          [Energy $epsilon slash (h dot #unit[kHz])$],
        ),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5),
    labels: ($−1.5$, $−1$, $−0.5$, $0$, $0.5$, $1$, $1.5$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (-0.75, -0.25, 0.25, 0.75),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )

  let patch-0 = (
    p0: (xlim.at(0), -186.16715833210657),
    p1: (xlim.at(1), -186.16715896454957),
    fill: colors(0).transparentize(50%),
    stroke: colors(0).transparentize(50%) + linewidth-very-narrow,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let patch-2 = (
    p0: (xlim.at(0), -38.84585098874768),
    p1: (xlim.at(1), -38.84616703624476),
    fill: colors(1).transparentize(50%),
    stroke: colors(1).transparentize(50%) + linewidth-very-narrow,
    transform: transform,
  )

  let stroke-line-3 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let patch-4 = (
    p0: (xlim.at(0), 60.51058175388426),
    p1: (xlim.at(1), 60.40529567432023),
    fill: colors(2).transparentize(50%),
    stroke: colors(2).transparentize(50%) + linewidth-very-narrow,
    transform: transform,
  )

  let stroke-line-5 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-5 = none
  let line-5 = (
    data: data.at("line-5"),
    stroke: stroke-line-5,
    marker: marker-line-5,
    transform: transform,
  )

  let patch-6 = (
    p0: (xlim.at(0), 87.94066594104295),
    p1: (xlim.at(1), 87.55602598531341),
    fill: colors(3).transparentize(50%),
    stroke: colors(3).transparentize(50%) + linewidth-very-narrow,
    transform: transform,
  )

  let stroke-line-7 = (
    paint: colors(3),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-7 = none
  let line-7 = (
    data: data.at("line-7"),
    stroke: stroke-line-7,
    marker: marker-line-7,
    transform: transform,
  )

  let patch-8 = (
    p0: (xlim.at(0), 166.07693296888436),
    p1: (xlim.at(1), 159.62200505311358),
    fill: colors(4).transparentize(50%),
    stroke: colors(4).transparentize(50%) + linewidth-very-narrow,
    transform: transform,
  )

  let patch-9 = (
    p0: (xlim.at(0), 198.60418053185484),
    p1: (xlim.at(1), 182.95939076952482),
    fill: colors(5).transparentize(50%),
    stroke: colors(5).transparentize(50%) + linewidth-very-narrow,
    transform: transform,
  )

  let stroke-line-10 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-10 = none
  let line-10 = (
    data: data.at("line-10"),
    stroke: stroke-line-10,
    marker: marker-line-10,
    transform: transform,
  )

  let label-band(label, y) = (
    position: transform((1.08, y)),
    body: place(
      right + bottom,
      text-box(text(size: 1em, fill: black, label)),
    ),
  )

  let labels = (
    label-band($n = 1$, -195),
    label-band($n = 2$, -48),
    label-band($n = 3$, 46),
    label-band($n = 4$, 85),
    label-band($n = 5$, 148),
    label-band($n = 6$, 185),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.rectangle(..patch-0)
  draw.rectangle(..patch-2)
  draw.rectangle(..patch-4)
  draw.rectangle(..patch-6)
  draw.rectangle(..patch-8)
  draw.rectangle(..patch-9)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-1)
  draw.line(..line-3)
  draw.line(..line-5)
  draw.line(..line-7)
  draw.line(..line-10)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  for label in labels { draw.text(..label) }
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-0.275, 0.015), ylim: (-285.0, 245.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 111%),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Superlattice phase $phi slash pi$]),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-0.30, -0.25, -0.20, -0.15, -0.10, -0.05, 0.0, 0.05),
    labels: ($−0.3$, $−0.25$, $−0.2$, $−0.15$, $−0.1$, $−0.05$, $0$, $0.05$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )

  let fill-collection-2 = colors(0).transparentize(fill-alpha)
  let stroke-collection-2 = (
    paint: colors(0),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let fill-collection-5 = colors(1).transparentize(fill-alpha)
  let stroke-collection-5 = (
    paint: colors(1),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-5 = transform
  let compute-scale-collection-5 = compute-scale
  let offset-transform-collection-5 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-5 = (
    data: data.at("collection-5"),
    fill: fill-collection-5,
    stroke: stroke-collection-5,
    transform: transform-collection-5,
    compute-scale: compute-scale-collection-5,
    offset-transform: offset-transform-collection-5,
  )

  let fill-collection-8 = colors(2).transparentize(fill-alpha)
  let stroke-collection-8 = (
    paint: colors(2),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-8 = transform
  let compute-scale-collection-8 = compute-scale
  let offset-transform-collection-8 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-8 = (
    data: data.at("collection-8"),
    fill: fill-collection-8,
    stroke: stroke-collection-8,
    transform: transform-collection-8,
    compute-scale: compute-scale-collection-8,
    offset-transform: offset-transform-collection-8,
  )

  let fill-collection-11 = colors(3).transparentize(fill-alpha)
  let stroke-collection-11 = (
    paint: colors(3),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-11 = transform
  let compute-scale-collection-11 = compute-scale
  let offset-transform-collection-11 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-11 = (
    data: data.at("collection-11"),
    fill: fill-collection-11,
    stroke: stroke-collection-11,
    transform: transform-collection-11,
    compute-scale: compute-scale-collection-11,
    offset-transform: offset-transform-collection-11,
  )

  let fill-collection-14 = colors(4).transparentize(fill-alpha)
  let stroke-collection-14 = (
    paint: colors(4),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-14 = transform
  let compute-scale-collection-14 = compute-scale
  let offset-transform-collection-14 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-14 = (
    data: data.at("collection-14"),
    fill: fill-collection-14,
    stroke: stroke-collection-14,
    transform: transform-collection-14,
    compute-scale: compute-scale-collection-14,
    offset-transform: offset-transform-collection-14,
  )

  let fill-collection-17 = colors(5).transparentize(fill-alpha)
  let stroke-collection-17 = (
    paint: colors(5),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-17 = transform
  let compute-scale-collection-17 = compute-scale
  let offset-transform-collection-17 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-17 = (
    data: data.at("collection-17"),
    fill: fill-collection-17,
    stroke: stroke-collection-17,
    transform: transform-collection-17,
    compute-scale: compute-scale-collection-17,
    offset-transform: offset-transform-collection-17,
  )

  let stroke-line-18 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-18 = none
  let line-18 = (
    data: ylim.map(y => (-0.25, y)),
    stroke: stroke-line-18,
    marker: marker-line-18,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.collection(..collection-2)
  draw.collection(..collection-5)
  draw.collection(..collection-8)
  draw.collection(..collection-11)
  draw.collection(..collection-14)
  draw.collection(..collection-17)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.line(..line-18)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 10.572%, right: 0.695%, top: 1.389%, bottom: 15.352%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: gutter,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
