// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let a0 = 70%
#let xlim = (15.0, 85.0)

#let label-xaxis = (
  position: (50.0%, 100% + 2.2em),
  body: place(
    center + top,
    text(
      size: 1em,
      fill: black,
      [Lattice depth $Vy1064 slash #unit[Erec]$],
    ),
  ),
)

#let label-yaxis = (
  position: (128%, 50.0%),
  body: rotate(
    -90.0deg,
    place(
      center + bottom,
      text(size: 1em, fill: black, bottom-edge: "descender", "Band composition"),
    ),
  ),
)

#let xaxis-major-ticks = (
  locs: (20, 40, 60, 80),
  labels: ($20$, $40$, $60$, $80$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (30, 50, 70, 90),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)
#let yaxis-major-ticks = (
  locs: (-0.5, 0.0, 0.5, 1.0, 1.5),
  labels: ($−0.5$, $0$, $0.5$, $1$, $1.5$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: (0.25, 0.75),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let axes-0(xlim: xlim, ylim: (79.0, 161.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (-11%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Transition frequency $fnm(1, eta) slash#unit[kHz]$]),
      ),
    ),
  )
  let yaxis-major-ticks = (
    locs: (70.0, 80.0, 90.0, 100.0, 110.0, 120.0, 130.0, 140.0, 150.0, 160.0, 170.0),
    labels: ($70$, $80$, $90$, $100$, $110$, $120$, $130$, $140$, $150$, $160$, $170$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(8).map(y => y * 10 + 85),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (2.0pt, 3.3pt), phase: 0.0pt),
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let step-0 = (47%, 15%)
  let step-1 = (60%, 9%)

  let C0 = colors(0)
  let stroke-line-4 = (
    paint: C0,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let gradient-stroke-line-4 = (
    ..stroke-line-4,
    paint: gradient.linear(..gradient-colors(
      C0.transparentize(80%),
      step-1,
      C0,
    )),
  )
  let marker-line-4 = none
  let line-4 = (
    data: data.at("line-4"),
    stroke: gradient-stroke-line-4,
    marker: marker-line-4,
    transform: transform,
  )

  let C1 = colors(1)
  let stroke-line-5 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let gradient-stroke-line-5 = (
    ..stroke-line-5,
    paint: gradient.linear(..gradient-colors(
      C1.transparentize(80%),
      step-0,
      C1,
      step-1,
      C1.transparentize(70%),
    )),
  )
  let marker-line-5 = none
  let line-5 = (
    data: data.at("line-5"),
    stroke: gradient-stroke-line-5,
    marker: marker-line-5,
    transform: transform,
  )

  let C2 = colors(2)
  let stroke-line-6 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let gradient-stroke-line-6 = (
    ..stroke-line-6,
    paint: gradient.linear(..gradient-colors(
      C2,
      step-0,
      C2.transparentize(90%),
    )),
  )
  let marker-line-6 = none
  let line-6 = (
    data: data.at("line-6"),
    stroke: gradient-stroke-line-6,
    marker: marker-line-6,
    transform: transform,
  )


  let legend-style = (
    location: bottom + right,
    title: none,
    columns: 1,
    row-gutter: 0.5em,
    item-gutter: 0.5em,
    column-gutter: 1.5em,
    handle-length: 2.0em,
    handle-height: 1.0em,
    fill: color.rgb(100.0%, 100.0%, 100.0%, 80.0%),
    stroke: none,
    frame: block.with(),
  )
  let uncoupled-legend-style = (
    ..legend-style,
    location: (20%, 1%),
  )
  let coupled-legend-style = (
    ..legend-style,
    location: (55%, 1%),
  )

  let uncoupled-legend-items = (
    (
      handle: legend.line2d.with(stroke: stroke-line-0, marker: marker-line-0),
      label: [$n = (3, 1)$],
    ),
    (
      handle: legend.line2d.with(stroke: stroke-line-1, marker: marker-line-1),
      label: [$n = (2, 2)$],
    ),
    (
      handle: legend.line2d.with(stroke: stroke-line-2, marker: marker-line-2),
      label: [$n = (1, 3)$],
    ),
  )

  let coupled-legend-items = (
    (
      handle: legend.line2d.with(stroke: stroke-line-4, marker: marker-line-4),
      label: [$eta = 2$],
    ),
    (
      handle: legend.line2d.with(stroke: stroke-line-5, marker: marker-line-5),
      label: [$eta = 3$],
    ),
    (
      handle: legend.line2d.with(stroke: stroke-line-6, marker: marker-line-6),
      label: [$eta = 4$],
    ),
  ).rev()

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-4)
  draw.line(..line-5)
  draw.line(..line-6)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  legend.legend(..uncoupled-legend-style, ..uncoupled-legend-items)
  legend.legend(..coupled-legend-style, ..coupled-legend-items)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: xlim, ylim: (-0.04671650433797497, 1.045302839182738), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let stroke-line-0 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: colors(2),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (2.0pt, 3.3pt), phase: 0.0pt),
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  // draw.text(..label-yaxis)
  axes.abc(..abc-style, 2)
}


#let axes-2(xlim: xlim, ylim: (-0.04107145294272894, 1.032421935113593), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let stroke-line-0 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: colors(1),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (2.0pt, 3.3pt), phase: 0.0pt),
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 3)
}


#let axes-3(xlim: xlim, ylim: (-0.04811381650782009, 1.0481397105671653), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")

  let stroke-line-0 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (2.0pt, 3.3pt), phase: 0.0pt),
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  // draw.text(..label-yaxis)
  axes.abc(..abc-style, 4)
}

#let grid-0() = {
  let padding = (left: 9.0%, right: 8.0%, top: 2.0%, bottom: 13.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (2.2fr, 1.0fr),
        rows: (1fr, 1fr, 1fr),
        column-gutter: gutter,
        row-gutter: gutter,
        axes.cell(
          position: (0, 0),
          shape: (1, 3),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (1, 1),
          shape: (1, 1),
          axes-2(),
        ),
        axes.cell(
          position: (1, 2),
          shape: (1, 1),
          axes-3(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 8.89cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
