// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let xaxis-label = [Offset $Delta slash t$]
#let xaxis-minor-tick-locs = range(-3, 3).map(x => x * 2 + 1)

#let inset-0(xlim: (-0.55, 0.55), ylim: (-12.228698317275027, 21.31468245190743), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-0.json")

  let xaxis-major-ticks = (
    locs: (0, 0, 0, 0, 0),
    labels: (),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0, 0, 0, 0),
    labels: (),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (0, 0, 0, 0, 0),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: color-left,
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: color-right,
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-major-ticks, transform)
}


#let axes-0(xlim: (-6.6, 6.6), ylim: (-6.6910387833280405, 6.6910387833280405), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111.21%),
    body: place(
      center + top,
      text(size: 1em, fill: black, xaxis-label),
    ),
  )
  let label-yaxis = (
    position: (-12.369%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Energy $epsilon slash t$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    labels: ($−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    labels: ($−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(-3, 3).map(y => y * 2 + 1),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: gradient.linear(
      color-left,
      color-left,
      color-right,
      color-right,
    ),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: gradient.linear(
      color-right,
      color-right,
      color-left,
      color-left,
    ),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let text-2 = (
    position: transform((5.2, -6.2)),
    body: place(
      right + bottom,
      text(size: 1em, fill: black, bottom-edge: "descender", ketg),
    ),
  )

  let text-3 = (
    position: transform((5.2, 6.2)),
    body: place(
      right + top,
      text(size: 1em, fill: black, kete),
    ),
  )

  let properties-inset-0 = (position: (3.0%, 35.0%), shape: (30.0%, 30.0%))

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-2)
  draw.text(..text-3)
  axes.inset(..properties-inset-0, inset-0())
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-6.6, 6.6), ylim: (-0.04251665810767906, 1.042516658107679), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 111.21%),
    body: place(
      center + top,
      text(size: 1em, fill: black, xaxis-label),
    ),
  )
  let label-yaxis = (
    position: (113.875%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        text(size: 1em, fill: black, [Ground-state composition $abs(phy.braket(psi, g))^2$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    labels: ($−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: xaxis-minor-tick-locs,
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (
      -0.2,
      0.0,
      0.2,
      0.4000000000000001,
      0.6000000000000001,
      0.8,
      1.0000000000000002,
      1.2000000000000002,
    ),
    labels: ($−0.2$, $0$, $0.2$, $0.4$, $0.6$, $0.8$, $1$, $1.2$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(0, 5).map(y => y * 0.2 + 0.1),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: color-left,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-right,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let text-2 = (
    position: transform((6, 0.04)),
    body: place(
      right + bottom,
      text(size: 1em, fill: color-left, bottom-edge: "descender", ketL),
    ),
  )

  let text-3 = (
    position: transform((6, 0.96)),
    body: place(
      right + top,
      text(size: 1em, fill: color-right, ketR),
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-2)
  draw.text(..text-3)
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 8.655%, right: 9.743%, top: 1.389%, bottom: 15.685%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: (1.702%,),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
