// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *
#import "@preview/cetz:0.4.1"

#let phase-ramp = cetz.canvas({
  import cetz.draw: *
  set-style(mark: (scale: 0.9))

  line(
    (0cm, 0),
    (3cm, 0),
    mark: (end: "triangle", fill: black),
    name: "arrow",
    stroke: black + linewidth-very-narrow,
  )

  content(
    (rel: (0, 0.3cm), to: "arrow"),
    $phase -> phase + pi slash 4$,
  )
})

#set page(width: 17cm, height: auto, margin: 0.9em)

#let axes-0(xlim: (148.98, 150.52), ylim: (-5.0, 235), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let label-xaxis = (
    position: (50.0%, 115%),
    body: place(
      center + top,
      box(
        width: 7cm,
        text(
          size: 1em,
          fill: black,
          [Frequency difference $abs(f_(n+1) - f_n) slash#unit[MHz]$],
        ),
      ),
    ),
  )
  let label-yaxis = (
    position: (-22%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        text(size: 1em, fill: black, [Occurrences]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (148.5, 149.0, 149.5, 150.0, 150.5, 151.0),
    labels: ($148.5$, $149$, $149.5$, $150$, $150.5$, $151$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (149.25, 149.75, 150.25),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0.0, 100.0, 200.0),
    labels: ($0$, $100$, $200$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (50, 150),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let patch-properties = (
    fill: color-data.lighten(30%),
    stroke: color-data.darken(30%) + linewidth-very-narrow,
    transform: transform,
  )
  let patch-0 = (
    p0: (149.05, 0.0),
    p1: (149.15, 0.0),
    ..patch-properties,
  )

  let patch-1 = (
    p0: (149.14999999999998, 1.0),
    p1: (149.24999999999997, 0.0),
    ..patch-properties,
  )

  let patch-2 = (
    p0: (149.25, 8.0),
    p1: (149.35, 0.0),
    ..patch-properties,
  )

  let patch-3 = (
    p0: (149.35, 28.0),
    p1: (149.45000000000002, 0.0),
    ..patch-properties,
  )

  let patch-4 = (
    p0: (149.45, 76.0),
    p1: (149.54999999999998, 0.0),
    ..patch-properties,
  )

  let patch-5 = (
    p0: (149.55, 152.0),
    p1: (149.65, 0.0),
    ..patch-properties,
  )

  let patch-6 = (
    p0: (149.64999999999998, 205.0),
    p1: (149.74999999999997, 0.0),
    ..patch-properties,
  )

  let patch-7 = (
    p0: (149.75, 223.0),
    p1: (149.85, 0.0),
    ..patch-properties,
  )

  let patch-8 = (
    p0: (149.84999999999997, 208.0),
    p1: (149.94999999999996, 0.0),
    ..patch-properties,
  )

  let patch-9 = (
    p0: (149.95, 127.0),
    p1: (150.04999999999998, 0.0),
    ..patch-properties,
  )

  let patch-10 = (
    p0: (150.04999999999998, 48.0),
    p1: (150.15, 0.0),
    ..patch-properties,
  )

  let patch-11 = (
    p0: (150.14999999999998, 19.0),
    p1: (150.24999999999997, 0.0),
    ..patch-properties,
  )

  let patch-12 = (
    p0: (150.25, 7.0),
    p1: (150.35, 0.0),
    ..patch-properties,
  )

  let patch-13 = (
    p0: (150.34999999999997, 1.0),
    p1: (150.44999999999996, 0.0),
    ..patch-properties,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.rectangle(..patch-0)
  draw.rectangle(..patch-1)
  draw.rectangle(..patch-2)
  draw.rectangle(..patch-3)
  draw.rectangle(..patch-4)
  draw.rectangle(..patch-5)
  draw.rectangle(..patch-6)
  draw.rectangle(..patch-7)
  draw.rectangle(..patch-8)
  draw.rectangle(..patch-9)
  draw.rectangle(..patch-10)
  draw.rectangle(..patch-11)
  draw.rectangle(..patch-12)
  draw.rectangle(..patch-13)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-1.125, 1.625), ylim: (-17.63281841736724, 18.289186764712056), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.abc(..abc-style, location: (1.15em, 0.3em), fill: none, 2)
}


#let axes-2(xlim: (-1.125, 1.625), ylim: (-10.289186764712056, 25.63281841736724), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
}


#let axes-3(xlim: (-1.125, 1.625), ylim: (-17.63281841736724, 18.289186764712063), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  axes.abc(..abc-style, location: (1.15em, 0.3em), fill: none, 3)
}


#let axes-4(xlim: (-1.125, 1.625), ylim: (-10.289186764712056, 25.63281841736724), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-4.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-data,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
}


#let grid-0() = {
  let padding = (left: 9.0%, right: 0.0%, top: 2.0%, bottom: 19.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1.0fr, 0.8fr, 0.8fr),
        rows: (1fr, 1fr),
        column-gutter: (1.298%, 1.299%),
        row-gutter: (15%,),
        axes.cell(
          position: (0, 0),
          shape: (1, 2),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (2, 0),
          shape: (1, 1),
          axes-2(),
        ),
        axes.cell(
          position: (1, 1),
          shape: (1, 1),
          axes-3(),
        ),
        axes.cell(
          position: (2, 1),
          shape: (1, 1),
          axes-4(),
        ),
      ),
    ),
  )
}

#let figure(width: 15.24cm, height: 6.55cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    {
      grid-0()
      std.place(
        top + right,
        dx: -18.35%,
        dy: 38%,
        phase-ramp,
      )
    },
  )
}

#figure()

