// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

// the transparent background looks weird on the atomic densities...
#let abc-style = (..abc-style, fill: none)

#let label-xaxis = (
  position: (50.0%, 120%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [$x slash#unit[μm]$]),
  ),
)

#let yaxis-major-ticks = (
  locs: (-100.0, -50.0, 0.0, 50.0, 100.0),
  labels: ($−100$, $−50$, $0$, $50$, $100$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: (-25, 25),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let xaxis-major-ticks = (
  locs: (-100.0, -50.0, 0.0, 50.0, 100.0),
  labels: ($−100$, $−50$, $0$, $50$, $100$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (-25, 25),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let axes-0(
  xlim: (-67.37634408602152, 67.37634408602152),
  ylim: (67.37634408602152, -67.37634408602152),
  dpi: 100.0,
) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let label-yaxis = (
    position: (-30%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(
          size: 1em,
          fill: black,
          bottom-edge: "descender",
          [$y slash#unit[μm]$],
        ),
      ),
    ),
  )

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/axes-0-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 1)
}


#let axes-1(
  xlim: (-67.37634408602152, 67.37634408602152),
  ylim: (67.37634408602152, -67.37634408602152),
  dpi: 100.0,
) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/axes-1-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let axes-2(
  xlim: (-67.37634408602152, 67.37634408602152),
  ylim: (67.37634408602152, -67.37634408602152),
  dpi: 100.0,
) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72
  let quad-mesh-0 = image(width: 100%, height: 100%, "data/axes-2-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 3)
}


#let axes-3(
  xlim: (-67.37634408602152, 67.37634408602152),
  ylim: (67.37634408602152, -67.37634408602152),
  dpi: 100.0,
) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/axes-3-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 4)
}

#let colorbar-4(lim: (0.0, 1.5)) = {
  let scale = 1 / (lim.at(1) - lim.at(0)) * 100%
  let shift = 50% - (lim.at(0) + lim.at(1)) / 2 * scale

  let transform(point) = {
    let (x, y) = point
    return (0, 100% - (y * scale + shift))
  }

  let label-colormap = (
    position: (450%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        box(
          width: 3cm,
          text(size: 1em, fill: black, [Atomic density $n(x, y)$]),
        ),
      ),
    ),
  )
  let colormap-major-ticks = (
    locs: (0.0, 0.5, 1.0, 1.5),
    labels: ($0$, $0.5$, $1$, $1.5$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let colormap-minor-ticks = (
    locs: (0.25, 0.75, 1.25),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  std.place(rect(width: 100%, height: 100%, fill: gradient-atomic-density, stroke: spine-stroke))
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..colormap-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..colormap-major-ticks, transform)
  draw.text(..label-colormap)
}


#let grid-0() = {
  let padding = (left: 8%, right: 7%, top: 5%, bottom: 23%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr, 1fr, 1fr, 2mm),
        rows: (1fr,),
        column-gutter: gutter-narrow,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (2, 0),
          shape: (1, 1),
          axes-2(),
        ),
        axes.cell(
          position: (3, 0),
          shape: (1, 1),
          axes-3(),
        ),
        axes.cell(
          position: (4, 0),
          shape: (1, 1),
          colorbar-4(),
        ),
      ),
    ),
  )
}

#let figure(width: 16cm, height: 4.37cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
