// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let axes-0(xlim: (-5.0, 255.0), ylim: (-1150.0, 1240.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111.347%),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Magnetic field $B slash T$]),
    ),
  )
  let label-yaxis = (
    position: (-14%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Energy $E slash (h dot #unit[MHz]$)]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-50.0, 0.0, 50.0, 100.0, 150.0, 200.0, 250.0, 300.0),
    labels: ($−50$, $0$, $50$, $100$, $150$, $200$, $250$, $300$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(11).map(x => x * 25),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-1500.0, -1000.0, -500.0, 0.0, 500.0, 1000.0, 1500.0),
    labels: ($−1500$, $−1000$, $−500$, $0$, $500$, $1000$, $1500$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(5).map(y => y * 500 - 750),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (paint: blue, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let stroke-line-3 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let stroke-line-4 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-4 = none
  let line-4 = (
    data: data.at("line-4"),
    stroke: stroke-line-4,
    marker: marker-line-4,
    transform: transform,
  )

  let stroke-line-5 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-5 = none
  let line-5 = (
    data: data.at("line-5"),
    stroke: stroke-line-5,
    marker: marker-line-5,
    transform: transform,
  )

  let stroke-line-6 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-6 = none
  let line-6 = (
    data: data.at("line-6"),
    stroke: stroke-line-6,
    marker: marker-line-6,
    transform: transform,
  )

  let stroke-line-7 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-7 = none
  let line-7 = (
    data: data.at("line-7"),
    stroke: stroke-line-7,
    marker: marker-line-7,
    transform: transform,
  )

  let stroke-line-8 = (paint: blue, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-8 = none
  let line-8 = (
    data: data.at("line-8"),
    stroke: stroke-line-8,
    marker: marker-line-8,
    transform: transform,
  )

  let stroke-line-9 = (paint: blue, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-9 = none
  let line-9 = (
    data: data.at("line-9"),
    stroke: stroke-line-9,
    marker: marker-line-9,
    transform: transform,
  )

  let stroke-line-10 = (paint: blue, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-10 = none
  let line-10 = (
    data: data.at("line-10"),
    stroke: stroke-line-10,
    marker: marker-line-10,
    transform: transform,
  )

  let stroke-line-11 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-11 = none
  let line-11 = (
    data: data.at("line-11"),
    stroke: stroke-line-11,
    marker: marker-line-11,
    transform: transform,
  )

  let stroke-line-12 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-12 = none
  let line-12 = (
    data: data.at("line-12"),
    stroke: stroke-line-12,
    marker: marker-line-12,
    transform: transform,
  )

  let stroke-line-13 = (paint: color.luma(50.0%), thickness: 0.4pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-13 = none
  let line-13 = (
    data: data.at("line-13"),
    stroke: stroke-line-13,
    marker: marker-line-13,
    transform: transform,
  )

  let stroke-line-14 = (paint: black, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-14 = none
  let line-14 = (
    data: data.at("line-14"),
    stroke: stroke-line-14,
    marker: marker-line-14,
    transform: transform,
  )

  let stroke-line-15 = (paint: black, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-15 = none
  let line-15 = (
    data: data.at("line-15"),
    stroke: stroke-line-15,
    marker: marker-line-15,
    transform: transform,
  )

  let stroke-line-16 = (paint: black, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-16 = none
  let line-16 = (
    data: data.at("line-16"),
    stroke: stroke-line-16,
    marker: marker-line-16,
    transform: transform,
  )

  let stroke-line-17 = (paint: black, thickness: 1.2pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-17 = none
  let line-17 = (
    data: data.at("line-17"),
    stroke: stroke-line-17,
    marker: marker-line-17,
    transform: transform,
  )

  let text-18 = (
    position: transform((0, -450)),
    body: place(
      left + bottom,
      text(size: 1em, fill: black, [$F = 9 slash 2$]),
    ),
  )

  let text-19 = (
    position: transform((0, 530)),
    body: place(
      left + bottom,
      text(size: 1em, fill: black, [$F = 7 slash 2$]),
    ),
  )

  let text-20 = (
    position: transform((250.0, -1070)),
    body: place(
      right + bottom,
      text(size: 1em, fill: black, [$m_F = -9 slash 2$]),
    ),
  )

  let text-21 = (
    position: transform((250.0, -150)),
    body: place(
      right + bottom,
      text(size: 1em, fill: black, [$m_F = +9 slash 2$]),
    ),
  )

  let text-22 = (
    position: transform((250.0, 350)),
    body: place(
      right + bottom,
      text(size: 1em, fill: black, [$m_F = +7 slash 2$]),
    ),
  )

  let text-23 = (
    position: transform((250.0, 1080)),
    body: place(
      right + bottom,
      text(size: 1em, fill: black, [$m_F = -7 slash 2$]),
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  draw.line(..line-4)
  draw.line(..line-5)
  draw.line(..line-6)
  draw.line(..line-7)
  draw.line(..line-8)
  draw.line(..line-9)
  draw.line(..line-10)
  draw.line(..line-11)
  draw.line(..line-12)
  draw.line(..line-13)
  draw.line(..line-14)
  draw.line(..line-15)
  draw.line(..line-16)
  draw.line(..line-17)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-18)
  draw.text(..text-19)
  draw.text(..text-20)
  draw.text(..text-21)
  draw.text(..text-22)
  draw.text(..text-23)
}


#let grid-0() = {
  let padding = (left: 17%, right: 2%, top: 2.8%, bottom: 15.3%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr,),
        rows: (1fr,),
        column-gutter: (),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
      ),
    ),
  )
}


#let figure(width: 10.16cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
