// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let xlim = (-0.30, 5.3)

#let label-xaxis = (
  position: (50.0%, 116.131%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [Holding time $tau slash #unit[s]$]),
  ),
)

#let xaxis-major-ticks = (
  locs: (-2.0, 0.0, 2.0, 4.0, 6.0),
  labels: ($−2$, $0$, $2$, $4$, $6$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: range(1, 7, step: 2),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let axes-0(xlim: xlim, ylim: (0.936, 1.004), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (-26.179%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Calibration factor #fita0]),
      ),
    ),
  )

  let yaxis-major-ticks = (
    locs: (0.92, 0.9400000000000001, 0.9600000000000001, 0.98, 1.0, 1.02),
    labels: ($0.92$, $0.94$, $0.96$, $0.98$, $1$, $1.02$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(0, 5).map(y => y * 0.02 + 0.93),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(color-stability-initial),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(color-stability-initial),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = none
  let marker-line-2 = markers.circle(
    markersize,
    ..marker-colors(color-stability-final),
  )
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let fill-collection-3 = ()
  let stroke-collection-3 = (
    paint: error-color(color-stability-final),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  let legend-style = (
    location: horizon + right,
    title: none,
    columns: 1,
    row-gutter: 0.5em,
    item-gutter: 0.1em,
    column-gutter: 1.5em,
    handle-length: 2.0em,
    handle-height: 1.0em,
    fill: color.rgb(100.0%, 100.0%, 100.0%, 80.0%),
    stroke: none,
    frame: block.with(),
  )
  let legend-items = (
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-0, marker: marker-line-0),
        caps: (:),
        bars: (y: stroke-collection-1),
      ),
      label: [initial],
    ),
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-2, marker: marker-line-2),
        caps: (:),
        bars: (y: stroke-collection-3),
      ),
      label: [final],
    ),
  ).rev()

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-2)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  legend.legend(..legend-style, ..legend-items)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: xlim, ylim: (133.0, 203.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-yaxis = (
    position: (-24.422%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Waist $wx1064 slash#unit[μm]$]),
      ),
    ),
  )

  let yaxis-major-ticks = (
    locs: (120.0, 140.0, 160.0, 180.0, 200.0, 220.0),
    labels: ($120$, $140$, $160$, $180$, $200$, $220$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(150, 210, step: 20),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(color-stability-initial),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(color-stability-initial),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = none
  let marker-line-2 = markers.circle(
    markersize,
    ..marker-colors(color-stability-final),
  )
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let fill-collection-3 = ()
  let stroke-collection-3 = (
    paint: error-color(color-stability-final),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-2)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 2)
}


#let axes-2(xlim: xlim, ylim: (-2.55, 1.55), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let label-yaxis = (
    position: (-20%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Position $fity0 slash#unit[μm]$]),
      ),
    ),
  )

  let yaxis-major-ticks = (
    locs: (-3.0, -2.0, -1.0, 0.0, 1.0, 2.0),
    labels: ($−3$, $−2$, $−1$, $0$, $1$, $2$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(0, 5).map(y => y - 2.5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(color-stability-initial),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(color-stability-initial),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = none
  let marker-line-2 = markers.circle(
    markersize,
    ..marker-colors(color-stability-final),
  )
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let fill-collection-3 = ()
  let stroke-collection-3 = (
    paint: error-color(color-stability-final),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-2)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 3)
}


#let grid-0() = {
  let padding = (left: 9%, right: 0.694%, top: 2.084%, bottom: 21.028%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr, 1fr),
        rows: (1fr,),
        column-gutter: (10%, 9%),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (2, 0),
          shape: (1, 1),
          axes-2(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 5.08cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
