// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let inset-xlim = (409.1, 413.9)
#let inset-ylim = (-0.05, 0.95)

#let xaxis-major-ticks = (
  locs: (410, 412),
  labels: ($410$, $412$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (411, 413),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)
#let yaxis-major-ticks = (
  locs: (0.0, 0.4, 0.8),
  labels: ($0$, $0.4$, $0.8$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: (0.2, 0.6),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let inset-0(xlim: inset-xlim, ylim: inset-ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-0.json")

  let stroke-line-0 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: red,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let inset-1(xlim: inset-xlim, ylim: inset-ylim, dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-1.json")

  let label-xaxis = (
    position: (50.0%, 100% + 2.2em),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Frequency $f slash#unit[MHz]$]),
    ),
  )

  let stroke-line-0 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: red,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
}


#let colorbar-0(lim: (413.2, 410.8)) = {
  let scale = 1 / (lim.at(1) - lim.at(0)) * 100%
  let shift = 50% - (lim.at(0) + lim.at(1)) / 2 * scale

  let transform(point) = {
    let (x, y) = point
    return (0, 100% - (y * scale + shift))
  }


  let label-colormap = (
    position: (-390%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        box(
          width: 5cm,
          text(size: 1em, fill: black, bottom-edge: "descender", [Frequency $f slash#unit[MHz]$]),
        ),
      ),
    ),
  )
  let colormap-major-ticks = (
    locs: (410.5, 411.0, 411.5, 412.0, 412.5, 413.0, 413.5),
    labels: ($410.5$, $411$, $411.5$, $412$, $412.5$, $413$, $413.5$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let colormap-minor-ticks = (
    locs: range(4).map(c => c * 0.5 + 411.25),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  std.place(rect(
    width: 100%,
    height: 100%,
    fill: std.gradient.linear(..colormap-phase, angle: 90deg),
    stroke: spine-stroke,
  ))
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..colormap-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..colormap-major-ticks, transform)
  draw.text(..label-colormap)
}


#let axes-1(
  xlim: (-53.11827956989248, 53.11827956989248),
  ylim: (53.11827956989248, -53.11827956989248),
  dpi: 100.0,
) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 100% + 2.2em),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Position $x slash#unit[μm]$]),
    ),
  )
  let label-yaxis = (
    position: (-17%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(
          size: 1em,
          fill: black,
          bottom-edge: "descender",
          [Position $y slash#unit[μm]$],
        ),
      ),
    ),
  )
  let secondary-label-yaxis = (
    position: (168%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        text(size: 1em, fill: black, [Mean occupation $n_L$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-60.0, -40.0, -20.0, 0.0, 20.0, 40.0, 60.0),
    labels: ($−60$, $−40$, $−20$, $0$, $20$, $40$, $60$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(6).map(y => y * 20 - 50),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-60.0, -40.0, -20.0, 0.0, 20.0, 40.0, 60.0),
    labels: ($−60$, $−40$, $−20$, $0$, $20$, $40$, $60$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(6).map(y => y * 20 - 50),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let gradient-quad-mesh-0 = std.gradient.linear(..colormap-phase)
  let colormap-quad-mesh-0(v, vmin: 410.8, vmax: 413.2) = gradient-quad-mesh-0.sample((v - vmin) / (vmax - vmin) * 100%)
  let quad-mesh-0 = (
    data: data.at("quad-mesh-0"),
    colormap: colormap-quad-mesh-0,
    transform: transform,
  )

  let properties-inset-0 = (
    position: (100.0% + gutter, 0.0%),
    shape: (50% - gutter / 2, 50% - gutter / 2),
  )

  let properties-inset-1 = (
    position: (100.0% + gutter, 50% + gutter / 2),
    shape: (50% - gutter / 2, 50% - gutter / 2),
  )

  let cell-size = 5.03225806451613
  let indicator-inset-0 = (
    target: (
      position: (27.67741935483871, -12.580645161290322 - cell-size),
      shape: (cell-size, -cell-size),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-0,
    connectors: (
      anchors: (bottom + left, top + left),
      stroke: inset-connector-stroke-dark,
    ),
  )

  let indicator-inset-1 = (
    target: (
      position: (2.516129032258065, 22.645161290322584 - cell-size),
      shape: (cell-size, -cell-size),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-1,
    connectors: (
      anchors: (bottom + left, top + left),
      stroke: inset-connector-stroke-dark,
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.quad-mesh(..quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..secondary-label-yaxis)
  axes.inset-indicator(..indicator-inset-0)
  axes.inset-indicator(..indicator-inset-1)
  axes.inset(..properties-inset-0, inset-0())
  axes.inset(..properties-inset-1, inset-1())
}

#let grid-0() = {
  let padding = (left: 12.0%, right: 32.0%, top: 2.0%, bottom: 15.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (gutter, 2.0fr),
        rows: (1fr,),
        column-gutter: (20.0%,),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          colorbar-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 12.85cm, height: 6.6cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
