// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let xlim = (13.6, 24.8)

#let label-xaxis = (
  position: (50.0%, 110%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [Lattice depth $Vx532 slash #unit[Erec]$]),
  ),
)

#let xaxis-major-ticks = (
  locs: range(14, 26, step: 2),
  labels: range(14, 26, step: 2).map(x => $#x$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)

#let xaxis-minor-ticks = (
  locs: range(15, 25, step: 2),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let inset-label-xaxis = (
  position: (50.0%, 150%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [Holding time $tau slash #unit[s]$]),
  ),
)

#let inset-xaxis-major-ticks = (
  locs: (0, 1, 2, 3, 4, 5),
  labels: ($0$, $1$, $2$, $3$, $4$, $5$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)

#let inset-xaxis-minor-ticks = (
  locs: range(0, 5).map(x => x + 0.5),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let inset-0(xlim: (-0.2499, 5.2501), ylim: (1.008, 1.022), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-0.json")

  let label-xaxis = inset-label-xaxis
  let xaxis-major-ticks = inset-xaxis-major-ticks
  let xaxis-minor-ticks = inset-xaxis-minor-ticks
  let yaxis-major-ticks = (
    locs: (1.0, 1.01, 1.02, 1.03),
    labels: ($1$, $1.01$, $1.02$, $1.03$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (1.015,),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(color-stability-final),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(color-stability-final),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
}


#let inset-1(xlim: (-0.2499, 5.2501), ylim: (108.5, 123.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-1.json")

  let label-xaxis = inset-label-xaxis
  let xaxis-major-ticks = inset-xaxis-major-ticks
  let xaxis-minor-ticks = inset-xaxis-minor-ticks
  let yaxis-major-ticks = (
    locs: (110.0, 120.0),
    labels: ($110$, $120$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (115.0,),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(color-stability-final),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(color-stability-final),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
}


#let axes-0(xlim: xlim, ylim: (0.678, 1.022), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (-17.481%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Calibration factor #fita0]),
      ),
    ),
  )

  let yaxis-major-ticks = (
    locs: (0.65, 0.7000000000000001, 0.75, 0.8, 0.8500000000000001, 0.9, 0.9500000000000001, 1.0, 1.05),
    labels: ($0.65$, $0.7$, $0.75$, $0.8$, $0.85$, $0.9$, $0.95$, $1$, $1.05$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(0, 6).map(y => y * 0.05 + 0.725),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(color-stability-initial),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(color-stability-initial),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  // Add this just for the legend...
  let stroke-line-2 = none
  let marker-line-2 = markers.circle(
    markersize,
    ..marker-colors(color-stability-final),
  )
  let stroke-collection-3 = (
    paint: error-color(color-stability-final),
    thickness: error-linewidth,
    dash: "solid",
  )

  let properties-inset-0 = (position: (38.0%, 2.0%), shape: (60.0%, 20.0%))

  let legend-style = (
    location: bottom + left,
    title: none,
    columns: 1,
    row-gutter: 0.5em,
    item-gutter: 0.0em,
    column-gutter: 1.5em,
    handle-length: 2.0em,
    handle-height: 1.0em,
    fill: color.rgb(100.0%, 100.0%, 100.0%, 80.0%),
    stroke: none,
    frame: block.with(),
  )
  let legend-items = (
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-0, marker: marker-line-0),
        caps: (:),
        bars: (y: stroke-collection-1),
      ),
      label: [initial],
    ),
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-2, marker: marker-line-2),
        caps: (:),
        bars: (y: stroke-collection-3),
      ),
      label: [final],
    ),
  ).rev()

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.inset(..properties-inset-0, inset-0())
  legend.legend(..legend-style, ..legend-items)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: xlim, ylim: (95.0, 185.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-yaxis = (
    position: (115.829%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        text(size: 1em, fill: black, [Horizontal waist $wx532^y slash#unit[μm]$]),
      ),
    ),
  )

  let yaxis-major-ticks = (
    locs: (80.0, 100.0, 120.0, 140.0, 160.0, 180.0, 200.0),
    labels: ($80$, $100$, $120$, $140$, $160$, $180$, $200$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(110, 190, step: 20),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(color-stability-initial),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(color-stability-initial),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let properties-inset-1 = (position: (10.0%, 2.0%), shape: (60.0%, 20.0%))

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.inset(..properties-inset-1, inset-1())
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 9.863%, right: 10.54%, top: 1.389%, bottom: 15.352%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: gutter,
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
