// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let xlim = (13.6, 24.8)

#let label-xaxis = (
  position: (50.0%, 110%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [Lattice depth $Vx532 slash #unit[Erec]$]),
  ),
)

#let inset-label-xaxis = (
  position: (50.0%, 150%),
  body: place(
    center + top,
    text(size: 1em, fill: black, [Holding time $tau slash #unit[s]$]),
  ),
)

#let inset-0(xlim: (-0.2499, 5.2501), ylim: (1.009, 1.021), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-0.json")

  let label-xaxis = inset-label-xaxis
  let xaxis-major-ticks = (
    locs: (0, 1, 2, 3, 4, 5),
    labels: ($0$, $1$, $2$, $3$, $4$, $5$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (
      -0.2,
      0.2,
      0.4,
      0.6000000000000001,
      0.8,
      1.2000000000000002,
      1.4000000000000001,
      1.6,
      1.8,
      2.2,
      2.4000000000000004,
      2.6,
      2.8000000000000003,
      3.2,
      3.4000000000000004,
      3.6,
      3.8000000000000003,
      4.2,
      4.4,
      4.6000000000000005,
      4.800000000000001,
      5.2,
    ),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (1.0, 1.01, 1.02, 1.03),
    labels: ($1$, $1.01$, $1.02$, $1.03$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (1.008, 1.012, 1.014, 1.016, 1.018),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: colors(1),
    stroke: black + 1.0pt,
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: color.rgb(83.529%, 36.863%, 0.0%, 100.0%),
    thickness: 2.0pt,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
}


#let inset-1(xlim: (-0.2499, 5.2501), ylim: (111.5, 123.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-1.json")

  let label-xaxis = inset-label-xaxis
  let xaxis-major-ticks = (
    locs: (0, 1, 2, 3, 4, 5),
    labels: ($0$, $1$, $2$, $3$, $4$, $5$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (
      -0.2,
      0.2,
      0.4,
      0.6000000000000001,
      0.8,
      1.2000000000000002,
      1.4000000000000001,
      1.6,
      1.8,
      2.2,
      2.4000000000000004,
      2.6,
      2.8000000000000003,
      3.2,
      3.4000000000000004,
      3.6,
      3.8000000000000003,
      4.2,
      4.4,
      4.6000000000000005,
      4.800000000000001,
      5.2,
    ),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (110.0, 115.0, 120.0, 125.0),
    labels: ($110$, $115$, $120$, $125$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (112.0, 113.0, 114.0, 116.0, 117.0, 118.0, 119.0, 121.0, 122.0, 123.0, 124.0),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: colors(1),
    stroke: black + 1.0pt,
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: color.rgb(83.529%, 36.863%, 0.0%, 100.0%),
    thickness: 2.0pt,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
}


#let axes-0(xlim: xlim, ylim: (0.675, 1.025), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (-17.481%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Calibration factor #fita0]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (12.5, 15.0, 17.5, 20.0, 22.5, 25.0),
    labels: ($12.5$, $15$, $17.5$, $20$, $22.5$, $25$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (
      13.5,
      14.0,
      14.5,
      15.5,
      16.0,
      16.5,
      17.0,
      18.0,
      18.5,
      19.0,
      19.5,
      20.5,
      21.0,
      21.5,
      22.0,
      23.0,
      23.5,
      24.0,
      24.5,
    ),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0.65, 0.7000000000000001, 0.75, 0.8, 0.8500000000000001, 0.9, 0.9500000000000001, 1.0, 1.05),
    labels: ($0.65$, $0.7$, $0.75$, $0.8$, $0.85$, $0.9$, $0.95$, $1$, $1.05$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (
      0.67,
      0.68,
      0.6900000000000001,
      0.7100000000000001,
      0.7200000000000001,
      0.7300000000000001,
      0.7400000000000001,
      0.7600000000000001,
      0.7700000000000001,
      0.7800000000000001,
      0.7900000000000001,
      0.8100000000000002,
      0.8200000000000002,
      0.8300000000000002,
      0.8400000000000002,
      0.8600000000000002,
      0.8700000000000002,
      0.8800000000000002,
      0.8900000000000002,
      0.9100000000000003,
      0.9200000000000003,
      0.9300000000000003,
      0.9400000000000003,
      0.9600000000000003,
      0.9700000000000003,
      0.9800000000000003,
      0.9900000000000003,
      1.0100000000000002,
      1.0200000000000005,
    ),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#0072b2ff"),
    stroke: black + 1.0pt,
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: color.rgb(0.0%, 44.706%, 69.804%, 100.0%),
    thickness: 2.0pt,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let properties-inset-0 = (position: (30.0%, 2.0%), shape: (68.0%, 20.0%))

  let legend-style = (
    location: bottom + left,
    title: none,
    columns: 1,
    row-gutter: 0.5em,
    item-gutter: 0.5em,
    column-gutter: 1.5em,
    handle-length: 2.0em,
    handle-height: 1.0em,
    fill: color.rgb(100.0%, 100.0%, 100.0%, 80.0%),
    stroke: color.rgb(0.0%, 0.0%, 0.0%, 80.0%),
    frame: block.with(),
  )
  let legend-items = (
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-0, marker: marker-line-0),
        caps: (:),
        bars: (y: stroke-collection-1),
      ),
      label: [initial],
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.inset(..properties-inset-0, inset-0())
  legend.legend(..legend-style, ..legend-items)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: xlim, ylim: (95.0, 185.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-yaxis = (
    position: (115.829%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        text(size: 1em, fill: black, [Horizontal waist $wx532^y slash#unit[μm]$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (12.5, 15.0, 17.5, 20.0, 22.5, 25.0),
    labels: ($12.5$, $15$, $17.5$, $20$, $22.5$, $25$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (
      13.5,
      14.0,
      14.5,
      15.5,
      16.0,
      16.5,
      17.0,
      18.0,
      18.5,
      19.0,
      19.5,
      20.5,
      21.0,
      21.5,
      22.0,
      23.0,
      23.5,
      24.0,
      24.5,
    ),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (80.0, 100.0, 120.0, 140.0, 160.0, 180.0, 200.0),
    labels: ($80$, $100$, $120$, $140$, $160$, $180$, $200$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (95.0, 105.0, 110.0, 115.0, 125.0, 130.0, 135.0, 145.0, 150.0, 155.0, 165.0, 170.0, 175.0, 185.0),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#0072b2ff"),
    stroke: black + 1.0pt,
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: color.rgb(0.0%, 44.706%, 69.804%, 100.0%),
    thickness: 2.0pt,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let properties-inset-1 = (position: (10.0%, 2.0%), shape: (68.0%, 20.0%))

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.inset(..properties-inset-1, inset-1())
  axes.abc(..abc-style, 2)
}


#let grid-0() = {
  let padding = (left: 9.863%, right: 10.54%, top: 1.389%, bottom: 15.352%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr),
        rows: (1fr,),
        column-gutter: (1.745%,),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 7.62cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: black,
    fill: white,
    grid-0(),
  )
}

#figure()
