// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let color-97 = colors(0)
#let color-95 = colors(1)
#let color-75 = colors(2)

#let axes-0(xlim: (187.0, 233.0), ylim: (-650.0, 650.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-xaxis = (
    position: (50.0%, 111%),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Magnetic field $B slash #unit[G]$]),
    ),
  )
  let label-yaxis = (
    position: (-13%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, [Scattering length $asc slash a_0$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (180.0, 190.0, 200.0, 210.0, 220.0, 230.0, 240.0),
    labels: ($180$, $190$, $200$, $210$, $220$, $230$, $240$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(0, 4).map(x => x * 10 + 195),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-800.0, -600.0, -400.0, -200.0, 0.0, 200.0, 400.0, 600.0, 800.0),
    labels: ($−800$, $−600$, $−400$, $−200$, $0$, $200$, $400$, $600$, $800$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(-5, 6).map(y => 100 * y),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-very-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: ((xlim.at(0), 0), (xlim.at(1), 0)),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: color-75,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: color-75,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let stroke-line-3 = (
    paint: color-75,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-3 = none
  let line-3 = (
    data: ((228.7, ylim.at(0)), (228.7, ylim.at(1))),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let stroke-line-4 = (
    paint: color-95,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-4 = none
  let line-4 = (
    data: data.at("line-4"),
    stroke: stroke-line-4,
    marker: marker-line-4,
    transform: transform,
  )

  let stroke-line-5 = (
    paint: color-95,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-5 = none
  let line-5 = (
    data: data.at("line-5"),
    stroke: stroke-line-5,
    marker: marker-line-5,
    transform: transform,
  )

  let stroke-line-6 = (
    paint: color-95,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-6 = none
  let line-6 = (
    data: ((224.21, ylim.at(0)), (224.21, ylim.at(1))),
    stroke: stroke-line-6,
    marker: marker-line-6,
    transform: transform,
  )

  let stroke-line-7 = (
    paint: color-97,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-7 = none
  let line-7 = (
    data: data.at("line-7"),
    stroke: stroke-line-7,
    marker: marker-line-7,
    transform: transform,
  )

  let stroke-line-8 = (
    paint: color-97,
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-8 = none
  let line-8 = (
    data: data.at("line-8"),
    stroke: stroke-line-8,
    marker: marker-line-8,
    transform: transform,
  )

  let stroke-line-9 = (
    paint: color-97,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-9 = none
  let line-9 = (
    data: ((202.1, ylim.at(0)), (202.1, ylim.at(1))),
    stroke: stroke-line-9,
    marker: marker-line-9,
    transform: transform,
  )

  let legend-style = (
    location: bottom + left,
    title: none,
    columns: 1,
    row-gutter: 0.5em,
    item-gutter: 0.5em,
    column-gutter: 1.5em,
    handle-length: 2.0em,
    handle-height: 1.0em,
    fill: color.rgb(100.0%, 100.0%, 100.0%, 80.0%),
    stroke: none,
    frame: block.with(),
  )
  let legend-items = (
    (
      handle: legend.line2d.with(stroke: stroke-line-1, marker: marker-line-1),
      label: mix(7, 5),
    ),
    (
      handle: legend.line2d.with(stroke: stroke-line-4, marker: marker-line-4),
      label: mix(9, 5),
    ),
    (
      handle: legend.line2d.with(stroke: stroke-line-7, marker: marker-line-7),
      label: mix(9, 7),
    ),
  ).rev()

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  draw.line(..line-4)
  draw.line(..line-5)
  draw.line(..line-6)
  draw.line(..line-7)
  draw.line(..line-8)
  draw.line(..line-9)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  legend.legend(..legend-style, ..legend-items)
}


#let grid-0() = {
  let padding = (left: 12.26%, right: 0.758%, top: 1.191%, bottom: 14.302%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr,),
        rows: (1fr,),
        column-gutter: (),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
      ),
    ),
  )
}


#let figure(width: 13.97cm, height: 8.89cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
