// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let z-forward-text(z) = block(
  height: 4mm,
  align(center + horizon, text(size: 1em, fill: black, [$zfwd = #qty[#z][μm]$])),
)

#let forward-xaxis-major-ticks = (
  locs: (-15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0),
  labels: ($−15$, $−10$, $−5$, $0$, $5$, $10$, $15$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let forward-xaxis-minor-ticks = (
  locs: (-7.5, -2.5, 2.5, 7.5),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let retro-xaxis-major-ticks = (
  locs: (-100.0, -50.0, 0.0, 50.0, 100.0),
  labels: ($−100$, $−50$, $0$, $50$, $100$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let retro-xaxis-minor-ticks = (
  locs: (-25, 25),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)
#let alpha-yaxis-major-ticks = (
  locs: (0.8, 0.9, 1.0, 1.1),
  labels: ($0.8$, $0.9$, $1$, $1.1$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let alpha-yaxis-minor-ticks = (
  locs: (0.95,),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let contrast-yaxis-major-ticks = (
  locs: (-1.0, 0.0, 1.0, 2.0, 3.0, 4.0),
  labels: ($−1$, $0$, $1$, $2$, $3$, $4$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let contrast-yaxis-minor-ticks = (
  locs: (0.5, 1.5, 2.5),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let inset-0(xlim: (0.0, 176.0), ylim: (176.0, 0.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let xaxis-major-ticks = (
    locs: (0.0, 100.0, 200.0),
    labels: ($0$, $100$, $200$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (20.0, 40.0, 60.0, 80.0, 120.0, 140.0, 160.0, 180.0),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0.0, 100.0, 200.0),
    labels: ($0$, $100$, $200$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (20.0, 40.0, 60.0, 80.0, 120.0, 140.0, 160.0, 180.0),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/inset-0-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let inset-1(xlim: (0.0, 176.0), ylim: (176.0, 0.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let xaxis-major-ticks = (
    locs: (0.0, 100.0, 200.0),
    labels: ($0$, $100$, $200$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (20.0, 40.0, 60.0, 80.0, 120.0, 140.0, 160.0, 180.0),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0.0, 100.0, 200.0),
    labels: ($0$, $100$, $200$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (20.0, 40.0, 60.0, 80.0, 120.0, 140.0, 160.0, 180.0),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/inset-1-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let inset-2(xlim: (0.0, 176.0), ylim: (176.0, 0.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let xaxis-major-ticks = (
    locs: (0.0, 100.0, 200.0),
    labels: ($0$, $100$, $200$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (20.0, 40.0, 60.0, 80.0, 120.0, 140.0, 160.0, 180.0),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0.0, 100.0, 200.0),
    labels: ($0$, $100$, $200$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (20.0, 40.0, 60.0, 80.0, 120.0, 140.0, 160.0, 180.0),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let quad-mesh-0 = image(width: 100%, height: 100%, "data/inset-2-quad-mesh-0.png")

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  std.place(top + left, quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-0(xlim: (-12.2, 12.2), ylim: (-20.8, 11.8), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let label-yaxis = (
    position: (-14%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(
          size: 1em,
          fill: black,
          bottom-edge: "descender",
          [Optimal position $zret slash#unit[μm]$],
        ),
      ),
    ),
  )

  let xaxis-major-ticks = forward-xaxis-major-ticks
  let xaxis-minor-ticks = forward-xaxis-minor-ticks

  let yaxis-major-ticks = (
    locs: (-25.0, -20.0, -15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0),
    labels: ($−25$, $−20$, $−15$, $−10$, $−5$, $0$, $5$, $10$, $15$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(6).map(y => y * 5 - 17.5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let stroke-line-3 = none
  let marker-line-3 = markers.square(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let fill-collection-4 = ()
  let stroke-collection-4 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-4 = transform
  let compute-scale-collection-4 = compute-scale
  let offset-transform-collection-4 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-4 = (
    data: data.at("collection-4"),
    fill: fill-collection-4,
    stroke: stroke-collection-4,
    transform: transform-collection-4,
    compute-scale: compute-scale-collection-4,
    offset-transform: offset-transform-collection-4,
  )

  let fill-collection-5 = ()
  let stroke-collection-5 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-5 = transform
  let compute-scale-collection-5 = compute-scale
  let offset-transform-collection-5 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-5 = (
    data: data.at("collection-5"),
    fill: fill-collection-5,
    stroke: stroke-collection-5,
    transform: transform-collection-5,
    compute-scale: compute-scale-collection-5,
    offset-transform: offset-transform-collection-5,
  )

  let properties-inset-0 = (position: (73.0%, 46.0%), shape: (25.0%, 25.0%))

  let properties-inset-1 = (position: (2.0%, 46.0%), shape: (25.0%, 25.0%))

  let properties-inset-2 = (position: (37.5%, 73.0%), shape: (25.0%, 25.0%))

  let indicator-inset-0 = (
    target: (
      position: (4.22, 0.181),
      shape: (0.001, 0.001),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-0,
    connectors: (
      anchors: (bottom + left, top + right),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-1 = (
    target: (
      position: (-10.92, -0.835),
      shape: (0.001, 0.001),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-1,
    connectors: (
      anchors: (top + left, top + right),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-2 = (
    target: (
      position: (-10.92, -18.468999999999998),
      shape: (0.001, 0.001),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-2,
    connectors: (
      anchors: (bottom + left, top + left),
      stroke: inset-connector-stroke,
    ),
  )

  let legend-style = (
    location: top + center,
    title: none,
    columns: 1,
    outset: 0.3em,
    row-gutter: 0.5em,
    item-gutter: 0.3em,
    column-gutter: 1.5em,
    handle-length: 2.0em,
    handle-height: 1.0em,
    fill: color.rgb(100.0%, 100.0%, 100.0%, 80.0%),
    stroke: none,
    frame: block.with(),
  )
  let legend-items = (
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-0, marker: marker-line-0),
        caps: (:),
        bars: (x: stroke-collection-1, y: stroke-collection-2),
      ),
      label: [Calibration factor],
    ),
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-3, marker: marker-line-3),
        caps: (:),
        bars: (x: stroke-collection-4, y: stroke-collection-5),
      ),
      label: [Resonance contrast],
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  draw.collection(..collection-4)
  draw.collection(..collection-5)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)

  // place the inset indicators below the lines/markers
  axes.inset-indicator(..indicator-inset-0)
  axes.inset-indicator(..indicator-inset-1)
  axes.inset-indicator(..indicator-inset-2)

  draw.line(..line-0)
  draw.line(..line-3)
  axes.spines(spines)
  draw.text(..label-yaxis)
  axes.inset(..properties-inset-0, inset-0())
  axes.inset(..properties-inset-1, inset-1())
  axes.inset(..properties-inset-2, inset-2())
  legend.legend(..legend-style, ..legend-items)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-12.2, 12.2), ylim: (0.968, 0.992), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 120%),
    body: place(
      center + top,
      text(size: 1em, fill: black, $zfwd slash#unit[μm]$),
    ),
  )
  let label-yaxis = (
    position: (-14%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(
          size: 1em,
          fill: black,
          bottom-edge: "descender",
          $max(fita0)$,
        ),
      ),
    ),
  )


  let xaxis-major-ticks = forward-xaxis-major-ticks
  let xaxis-minor-ticks = forward-xaxis-minor-ticks

  let yaxis-major-ticks = (
    locs: (0.96, 0.97, 0.98, 0.99, 1.0),
    labels: ($0.96$, $0.97$, $0.98$, $0.99$, $1$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (0.975, 0.985),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 2)
}


#let axes-2(xlim: (-53.0, 53.0), ylim: (0.885, 1.015), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let xaxis-major-ticks = retro-xaxis-major-ticks
  let xaxis-minor-ticks = retro-xaxis-minor-ticks
  let yaxis-major-ticks = alpha-yaxis-major-ticks
  let yaxis-minor-ticks = alpha-yaxis-minor-ticks

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let text-3 = (
    position: (95.0%, 0.3em),
    body: place(
      right + top,
      z-forward-text(-10.9),
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..text-3)
  axes.abc(..abc-style, 3)
}


#let axes-3(xlim: (-53.0, 53.0), ylim: (0.885, 1.015), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")

  let label-yaxis = (
    position: (-24%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Calibration factor $fita0$]),
      ),
    ),
  )

  let xaxis-major-ticks = retro-xaxis-major-ticks
  let xaxis-minor-ticks = retro-xaxis-minor-ticks
  let yaxis-major-ticks = alpha-yaxis-major-ticks
  let yaxis-minor-ticks = alpha-yaxis-minor-ticks

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let text-3 = (
    position: (95.0%, 0.3em),
    body: place(
      right + top,
      z-forward-text(-0.8),
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-yaxis)
  draw.text(..text-3)
  axes.abc(..abc-style, 4)
}


#let axes-4(xlim: (-53.0, 53.0), ylim: (0.885, 1.015), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-4.json")

  let label-xaxis = (
    position: (50.0%, 120%),
    body: place(
      center + top,
      text(size: 1em, fill: black, $zret slash#unit[μm]$),
    ),
  )

  let xaxis-major-ticks = retro-xaxis-major-ticks
  let xaxis-minor-ticks = retro-xaxis-minor-ticks
  let yaxis-major-ticks = alpha-yaxis-major-ticks
  let yaxis-minor-ticks = alpha-yaxis-minor-ticks

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(0)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let text-3 = (
    position: (95.0%, 0.3em),
    body: place(
      right + top,
      z-forward-text(10.1),
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..text-3)
  axes.abc(..abc-style, 5)
}


#let axes-5(xlim: (-53.0, 53.0), ylim: (-0.1, 3.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-5.json")

  let yaxis-major-ticks = contrast-yaxis-major-ticks
  let yaxis-minor-ticks = contrast-yaxis-minor-ticks

  let stroke-line-0 = none
  let marker-line-0 = markers.square(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  // std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let axes-6(xlim: (-53.0, 53.0), ylim: (-0.1, 3.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-6.json")

  let label-yaxis = (
    position: (120%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        box(
          width: 6cm,
          text(
            size: 1em,
            fill: black,
            [Resonance contrast $fitaR slash fitsR$],
          ),
        ),
      ),
    ),
  )

  let yaxis-major-ticks = contrast-yaxis-major-ticks
  let yaxis-minor-ticks = contrast-yaxis-minor-ticks

  let stroke-line-0 = none
  let marker-line-0 = markers.square(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  // std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-yaxis)
}


#let axes-7(xlim: (-53.0, 53.0), ylim: (-0.1, 3.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-7.json")

  let yaxis-major-ticks = contrast-yaxis-major-ticks
  let yaxis-minor-ticks = contrast-yaxis-minor-ticks

  let stroke-line-0 = none
  let marker-line-0 = markers.square(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (
    paint: error-color(colors(1)),
    thickness: error-linewidth,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  // std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let grid-0() = {
  let padding = (left: 10.0%, right: 8%, top: 2.0%, bottom: 10.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (2fr, .955fr),
        rows: (1fr, 1fr, 1fr),
        column-gutter: 12%,
        row-gutter: gutter,
        axes.cell(
          position: (0, 0),
          shape: (1, 2),
          axes-0(),
        ),
        axes.cell(
          position: (0, 2),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          {
            axes-2()
            axes-5()
          },
        ),
        axes.cell(
          position: (1, 1),
          shape: (1, 1),
          {
            axes-3()
            axes-6()
          },
        ),
        axes.cell(
          position: (1, 2),
          shape: (1, 1),
          {
            axes-4()
            axes-7()
          },
        ),
      ),
    ),
  )
}


#let figure(width: 13.52cm, height: 11.43cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
