// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

#let xaxis-major-ticks = (
  locs: (-1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0),
  labels: ($−1$, $0$, $1$, $2$, $3$, $4$, $5$, $6$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: range(5).map(x => x + 0.5),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)

#let yaxis-major-ticks = (
  locs: (-1.0, 0.0, 1.0, 2.0),
  labels: ($−1$, $0$, $1$, $2$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: (-0.5, 0.5),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

#let axes-0(xlim: (-0.1, 5.1), ylim: (-0.65, 1.15), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = none
  let marker-line-1 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  axes.abc(..abc-style, 1)
}


#let axes-1(xlim: (-0.1, 5.1), ylim: (-0.65, 1.15), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let label-xaxis = (
    position: (50.0%, 100% + 2.2em),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Time $tau slash#unit[ms]$]),
    ),
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = none
  let marker-line-1 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-1)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  axes.abc(..abc-style, 2)
}


#let axes-2(xlim: (-0.225, 4.725), ylim: (-0.05, 1.05), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let label-xaxis = (
    position: (50.0%, 100% + 2.2em),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Modulation amplitude #K0]),
    ),
  )
  let label-yaxis = (
    position: (120%, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + top,
        text(size: 1em, fill: black, [Tunneling amplitude $ateffn(l) slash t$]),
      ),
    ),
  )
  let secondary-label-yaxis = (
    position: (0% - 9.2cm, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Occupation contrast #calC]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (-2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−2$, $0$, $2$, $4$, $6$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (1, 3, 5),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0, 0.5, 1),
    labels: ($0$, $0.5$, $1$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (0.25, 0.75),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(1)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(1).transparentize(25.0%),
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = none
  let marker-line-2 = markers.circle(
    markersize,
    ..marker-colors(colors(0)),
  )
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let stroke-line-3 = (
    paint: colors(0).transparentize(25.0%),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: (array: (7.4pt, 3.2pt), phase: 0.0pt),
  )
  let marker-line-3 = none
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let stroke-line-4 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (2.0pt, 3.3pt), phase: 0.0pt),
  )
  let marker-line-4 = none
  let line-4 = (
    data: ylim.map(y => (2.4, y)),
    stroke: stroke-line-4,
    marker: marker-line-4,
    transform: transform,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-1)
  draw.line(..line-3)
  draw.line(..line-4)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-minor-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..secondary-label-yaxis)
  axes.abc(..abc-style, 3)
}


#let axes-3(xlim: (0.0, 1.0), ylim: (0.0, 1.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let xaxis-major-ticks = (
    locs: (0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0),
    labels: ($0$, $0.2$, $0.4$, $0.6$, $0.8$, $1$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: (1, 3),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0),
    labels: ($0$, $0.2$, $0.4$, $0.6$, $0.8$, $1$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: (
      0.05,
      0.1,
      0.15000000000000002,
      0.25,
      0.30000000000000004,
      0.35000000000000003,
      0.45,
      0.5,
      0.55,
      0.65,
      0.7000000000000001,
      0.75,
      0.8500000000000001,
      0.9,
      0.9500000000000001,
    ),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-minor-ticks, transform)
  axes.xaxis-ticks(show-ticks: (), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (), show-labels: (), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-yaxis)
  axes.abc(..abc-style, 4)
}


#let grid-0() = {
  let padding = (left: 7.0%, right: 9.0%, top: 2.0%, bottom: 20.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (2fr, 1fr),
        rows: (1fr, 1fr),
        column-gutter: gutter,
        row-gutter: gutter,
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (0, 1),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 2),
          axes-2(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 5.31cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
