// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *

#set page(width: 17cm, height: auto, margin: 0.9em)

// set the global ticks for all insets here...
#let xaxis-major-ticks = (
  locs: (0, 2, 4),
  labels: ($0$, $2$, $4$),
  tick-style: xaxis-major-tick-style,
  label-style: xaxis-major-label-style,
)
#let xaxis-minor-ticks = (
  locs: (1, 3, 5),
  labels: (),
  tick-style: xaxis-minor-tick-style,
  label-style: xaxis-minor-label-style,
)
#let yaxis-major-ticks = (
  locs: (-1.0, -0.5, 0.0, 0.5, 1.0, 1.5),
  labels: ($−1$, $−0.5$, $0$, $0.5$, $1$, $1.5$),
  tick-style: yaxis-major-tick-style,
  label-style: yaxis-major-label-style,
)
#let yaxis-minor-ticks = (
  locs: (-0.25, 0.25, 0.75),
  labels: (),
  tick-style: yaxis-minor-tick-style,
  label-style: yaxis-minor-label-style,
)

// set the global markers and strokes for all insets here...
#let stroke-line-0 = none
#let marker-line-0 = markers.circle(
  linewidth,
  fill: colors(0),
  stroke: black + linewidth-very-narrow,
)

#let fill-collection-1 = ()
#let stroke-collection-1 = (
  paint: colors(0),
  thickness: linewidth,
  dash: "solid",
)

#let stroke-line-2 = (
  paint: colors(1).transparentize(50.0%),
  thickness: linewidth,
  cap: "butt",
  join: "round",
  dash: "solid",
)
#let marker-line-2 = none

#let fill-collection-3 = colors(1)
#let stroke-collection-3 = (
  paint: colors(1),
  thickness: linewidth-very-narrow,
  dash: "solid",
)

#let inset-0(xlim: (-0.2, 5.2), ylim: (-0.75, 1.15), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-0.json")

  let label-yaxis = (
    position: (-3.1em, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        box(
          width: 6cm,
          text(
            size: 1em,
            fill: black,
            bottom-edge: "descender",
            [Occupation contrast #calC],
          ),
        ),
      ),
    ),
  )

  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    linewidth,
    fill: colors(0),
    stroke: black + linewidth-very-narrow,
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: colors(0),
    thickness: linewidth,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: colors(1).transparentize(50.0%),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let fill-collection-3 = colors(1)
  let stroke-collection-3 = (
    paint: colors(1),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-2)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..label-yaxis)
}


#let inset-1(xlim: (-0.2, 5.2), ylim: (-0.75, 1.15), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-1.json")

  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-2)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let inset-2(xlim: (-0.2, 5.2), ylim: (-0.75, 1.15), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-2.json")

  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-2)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let inset-3(xlim: (-0.2, 5.2), ylim: (-0.75, 1.15), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/inset-3.json")

  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  draw.line(..line-2)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  axes.xaxis-ticks(show-ticks: (top,), show-labels: (top,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let axes-0(xlim: (0.43, 1.23), ylim: (-0.5, 0.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let title-main = (
    position: (50.0%, -69.96%),
    body: place(
      center + bottom,
      text(size: 1em, fill: black, [Time $tau slash#unit[ms]$]),
    ),
  )

  let label-xaxis = (
    position: (50.0%, 111.393%),
    body: place(
      center + top,
      text(size: 1em, fill: black, [Normalized driving frequency $h nu slash abs(U)$]),
    ),
  )
  let label-yaxis = (
    position: (-3.1em, 50.0%),
    body: rotate(
      -90.0deg,
      place(
        center + bottom,
        text(size: 1em, fill: black, bottom-edge: "descender", [Energy $E slash h nu$]),
      ),
    ),
  )
  let xaxis-major-ticks = (
    locs: (0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3),
    labels: ($0.4$, $0.5$, $0.6$, $0.7$, $0.8$, $0.9$, $1$, $1.1$, $1.2$, $1.3$),
    tick-style: xaxis-major-tick-style,
    label-style: xaxis-major-label-style,
  )
  let xaxis-minor-ticks = (
    locs: range(8).map(x => x * 0.1 + 0.45),
    labels: (),
    tick-style: xaxis-minor-tick-style,
    label-style: xaxis-minor-label-style,
  )
  let yaxis-major-ticks = (
    locs: (-0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.6),
    labels: ($−0.6$, $−0.4$, $−0.2$, $0$, $0.2$, $0.4$, $0.6$),
    tick-style: yaxis-major-tick-style,
    label-style: yaxis-major-label-style,
  )
  let yaxis-minor-ticks = (
    locs: range(6).map(y => y * 0.2 - 0.5),
    labels: (),
    tick-style: yaxis-minor-tick-style,
    label-style: yaxis-minor-label-style,
  )

  let marker-colors(color) = (
    fill: color.lighten(20%),
    stroke: color.darken(20%) + linewidth-very-narrow,
  )
  let error-color(color) = color.darken(20%)
  let theory-color(color) = color.lighten(20%)

  let theory-alpha-first(color) = {
    let transparency = (100%,) * 3 + (0%,) * 4
    std.gradient.linear(
      ..transparency.map(a => color.transparentize(a)),
    )
  }

  let theory-alpha-second(color) = {
    let transparency = (100%,) * 3 + (0%,) * 1
    std.gradient.linear(
      ..transparency.map(a => color.transparentize(a)),
    )
  }

  let theory-hatch(color) = hatch.hatch(
    pattern: "..",
    stroke: black + 0.3pt,
    fill: theory-color(color),
    size: (20pt, 20pt),
  )

  // first order stuff...
  let stroke-line-0 = none
  let marker-line-0 = markers.circle(
    markersize,
    ..marker-colors(colors(2)),
  )
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let fill-collection-1 = ()
  let stroke-collection-1 = (
    paint: error-color(colors(2)),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = theory-alpha-first(colors(2))
  let stroke-collection-2 = (
    paint: theory-alpha-first(black),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let stroke-line-3 = none
  let marker-line-3 = markers.circle(
    markersize,
    ..marker-colors(colors(3)),
  )
  let line-3 = (
    data: data.at("line-3"),
    stroke: stroke-line-3,
    marker: marker-line-3,
    transform: transform,
  )

  let fill-collection-4 = ()
  let stroke-collection-4 = (
    paint: error-color(colors(3)),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-4 = transform
  let compute-scale-collection-4 = compute-scale
  let offset-transform-collection-4 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-4 = (
    data: data.at("collection-4"),
    fill: fill-collection-4,
    stroke: stroke-collection-4,
    transform: transform-collection-4,
    compute-scale: compute-scale-collection-4,
    offset-transform: offset-transform-collection-4,
  )

  let fill-collection-5 = theory-alpha-first(colors(3))
  let stroke-collection-5 = (
    paint: theory-alpha-first(black),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-5 = transform
  let compute-scale-collection-5 = compute-scale
  let offset-transform-collection-5 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-5 = (
    data: data.at("collection-5"),
    fill: fill-collection-5,
    stroke: stroke-collection-5,
    transform: transform-collection-5,
    compute-scale: compute-scale-collection-5,
    offset-transform: offset-transform-collection-5,
  )

  let stroke-line-6 = none
  let marker-line-6 = markers.circle(
    markersize,
    ..marker-colors(colors(4)),
  )
  let line-6 = (
    data: data.at("line-6"),
    stroke: stroke-line-6,
    marker: marker-line-6,
    transform: transform,
  )

  let fill-collection-7 = ()
  let stroke-collection-7 = (
    paint: error-color(colors(4)),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-7 = transform
  let compute-scale-collection-7 = compute-scale
  let offset-transform-collection-7 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-7 = (
    data: data.at("collection-7"),
    fill: fill-collection-7,
    stroke: stroke-collection-7,
    transform: transform-collection-7,
    compute-scale: compute-scale-collection-7,
    offset-transform: offset-transform-collection-7,
  )

  let fill-collection-8 = theory-alpha-first(colors(4))
  let stroke-collection-8 = (
    paint: theory-alpha-first(black),
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-8 = transform
  let compute-scale-collection-8 = compute-scale
  let offset-transform-collection-8 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-8 = (
    data: data.at("collection-8"),
    fill: fill-collection-8,
    stroke: stroke-collection-8,
    transform: transform-collection-8,
    compute-scale: compute-scale-collection-8,
    offset-transform: offset-transform-collection-8,
  )


  // second order stuff...
  let stroke-line-9 = none
  let marker-line-9 = markers.thin-diamond(
    markersize,
    ..marker-colors(colors(2)),
  )
  let line-9 = (
    data: data.at("line-9"),
    stroke: stroke-line-9,
    marker: marker-line-9,
    transform: transform,
  )

  let fill-collection-10 = ()
  let stroke-collection-10 = (
    paint: error-color(colors(2)),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-10 = transform
  let compute-scale-collection-10 = compute-scale
  let offset-transform-collection-10 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-10 = (
    data: data.at("collection-10"),
    fill: fill-collection-10,
    stroke: stroke-collection-10,
    transform: transform-collection-10,
    compute-scale: compute-scale-collection-10,
    offset-transform: offset-transform-collection-10,
  )

  let fill-collection-11 = theory-hatch(colors(2))
  let stroke-collection-11 = (
    paint: black,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-11 = transform
  let compute-scale-collection-11 = compute-scale
  let offset-transform-collection-11 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-11 = (
    data: data.at("collection-11"),
    fill: fill-collection-11,
    stroke: stroke-collection-11,
    transform: transform-collection-11,
    compute-scale: compute-scale-collection-11,
    offset-transform: offset-transform-collection-11,
  )

  let fill-collection-12 = theory-hatch(colors(2))
  let stroke-collection-12 = (
    paint: black,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-12 = transform
  let compute-scale-collection-12 = compute-scale
  let offset-transform-collection-12 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-12 = (
    data: data.at("collection-12"),
    fill: fill-collection-12,
    stroke: stroke-collection-12,
    transform: transform-collection-12,
    compute-scale: compute-scale-collection-12,
    offset-transform: offset-transform-collection-12,
  )

  let stroke-line-13 = none
  let marker-line-13 = markers.thin-diamond(
    markersize,
    ..marker-colors(colors(3)),
  )
  let line-13 = (
    data: data.at("line-13"),
    stroke: stroke-line-13,
    marker: marker-line-13,
    transform: transform,
  )

  let fill-collection-14 = ()
  let stroke-collection-14 = (
    paint: error-color(colors(3)),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-14 = transform
  let compute-scale-collection-14 = compute-scale
  let offset-transform-collection-14 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-14 = (
    data: data.at("collection-14"),
    fill: fill-collection-14,
    stroke: stroke-collection-14,
    transform: transform-collection-14,
    compute-scale: compute-scale-collection-14,
    offset-transform: offset-transform-collection-14,
  )

  let fill-collection-15 = theory-hatch(colors(3))
  let stroke-collection-15 = (
    paint: black,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-15 = transform
  let compute-scale-collection-15 = compute-scale
  let offset-transform-collection-15 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-15 = (
    data: data.at("collection-15"),
    fill: fill-collection-15,
    stroke: stroke-collection-15,
    transform: transform-collection-15,
    compute-scale: compute-scale-collection-15,
    offset-transform: offset-transform-collection-15,
  )

  let fill-collection-16 = theory-hatch(colors(3))
  let stroke-collection-16 = (
    paint: black,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-16 = transform
  let compute-scale-collection-16 = compute-scale
  let offset-transform-collection-16 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-16 = (
    data: data.at("collection-16"),
    fill: fill-collection-16,
    stroke: stroke-collection-16,
    transform: transform-collection-16,
    compute-scale: compute-scale-collection-16,
    offset-transform: offset-transform-collection-16,
  )

  let stroke-line-17 = none
  let marker-line-17 = markers.thin-diamond(
    markersize,
    ..marker-colors(colors(4)),
  )
  let line-17 = (
    data: data.at("line-17"),
    stroke: stroke-line-17,
    marker: marker-line-17,
    transform: transform,
  )

  let fill-collection-18 = ()
  let stroke-collection-18 = (
    paint: error-color(colors(4)),
    thickness: linewidth-narrow,
    dash: "solid",
  )
  let transform-collection-18 = transform
  let compute-scale-collection-18 = compute-scale
  let offset-transform-collection-18 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-18 = (
    data: data.at("collection-18"),
    fill: fill-collection-18,
    stroke: stroke-collection-18,
    transform: transform-collection-18,
    compute-scale: compute-scale-collection-18,
    offset-transform: offset-transform-collection-18,
  )

  let fill-collection-19 = theory-hatch(colors(4))
  let stroke-collection-19 = (
    paint: black,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-19 = transform
  let compute-scale-collection-19 = compute-scale
  let offset-transform-collection-19 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-19 = (
    data: data.at("collection-19"),
    fill: fill-collection-19,
    stroke: stroke-collection-19,
    transform: transform-collection-19,
    compute-scale: compute-scale-collection-19,
    offset-transform: offset-transform-collection-19,
  )

  let fill-collection-20 = theory-hatch(colors(4))
  let stroke-collection-20 = (
    paint: black,
    thickness: linewidth-very-narrow,
    dash: "solid",
  )
  let transform-collection-20 = transform
  let compute-scale-collection-20 = compute-scale
  let offset-transform-collection-20 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-20 = (
    data: data.at("collection-20"),
    fill: fill-collection-20,
    stroke: stroke-collection-20,
    transform: transform-collection-20,
    compute-scale: compute-scale-collection-20,
    offset-transform: offset-transform-collection-20,
  )

  let stroke-line-21 = (
    paint: luma(50%),
    thickness: linewidth-very-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-21 = none
  let line-21 = (
    data: ylim.map(y => (data.at("line-21").at(0).at(0), y)),
    stroke: stroke-line-21,
    marker: marker-line-21,
    transform: transform,
  )

  let stroke-line-23 = (
    paint: color.luma(50.0%),
    thickness: linewidth-very-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-23 = none
  let line-23 = (
    data: ylim.map(y => (data.at("line-23").at(0).at(0), y)),
    stroke: stroke-line-23,
    marker: marker-line-23,
    transform: transform,
  )

  let stroke-line-25 = (
    paint: color.luma(50.0%),
    thickness: linewidth-very-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-25 = none
  let line-25 = (
    data: ylim.map(y => (data.at("line-25").at(0).at(0), y)),
    stroke: stroke-line-25,
    marker: marker-line-25,
    transform: transform,
  )

  let stroke-line-27 = (
    paint: color.luma(50.0%),
    thickness: linewidth-very-narrow,
    cap: "butt",
    join: "round",
    dash: (array: (3.33pt, 1.44pt), phase: 0.0pt),
  )
  let marker-line-27 = none
  let line-27 = (
    data: ylim.map(y => (data.at("line-27").at(0).at(0), y)),
    stroke: stroke-line-27,
    marker: marker-line-27,
    transform: transform,
  )

  let properties-inset-0 = (position: (0.0%, -58.0%), shape: (23.5%, 50.0%))
  let properties-inset-1 = (position: (25.5%, -58.0%), shape: (23.5%, 50.0%))
  let properties-inset-2 = (position: (51.0%, -58.0%), shape: (23.5%, 50.0%))
  let properties-inset-3 = (position: (76.5%, -58.0%), shape: (23.5%, 50.0%))

  let indicator-inset-0 = (
    target: (
      position: (0.5430491232216836, 0.5),
      shape: (0, 0),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-0,
    connectors: (
      anchors: (bottom + left, bottom + right),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-1 = (
    target: (
      position: (0.6154556729845748, 0.5),
      shape: (0, 0),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-1,
    connectors: (
      anchors: (bottom + left, bottom + right),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-2 = (
    target: (
      position: (0.9774884217990306, 0.5),
      shape: (0, 0),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-2,
    connectors: (
      anchors: (bottom + left, bottom + right),
      stroke: inset-connector-stroke,
    ),
  )

  let indicator-inset-3 = (
    target: (
      position: (1.0498949715619217, 0.5),
      shape: (0, 0),
      transform: transform,
      stroke: inset-indicator-stroke,
    ),
    source: properties-inset-3,
    connectors: (
      anchors: (bottom + left, bottom + right),
      stroke: inset-connector-stroke,
    ),
  )

  let legend-style = (
    location: top + center,
    title: none,
    columns: 2,
    outset: 0.3em,
    row-gutter: 0.5em,
    item-gutter: 0.5em,
    column-gutter: -0.5em,
    handle-length: 2.0em,
    handle-height: 1.0em,
    fill: color.rgb(100.0%, 100.0%, 100.0%, 80.0%),
    stroke: none,
    frame: block.with(),
  )

  let legend-handle(color, marker) = legend.errorbar.with(
    data: (
      stroke: none,
      marker: marker(markersize, ..marker-colors(color)),
    ),
    caps: (:),
    bars: (
      y: (
        paint: error-color(color),
        thickness: linewidth-narrow,
        dash: "solid",
      ),
    ),
  )

  let legend-color = luma(70%)
  let legend-items = (
    (
      handle: legend-handle(legend-color, markers.circle),
      label: [],
    ),
    (
      handle: legend.rectangle.with(
        fill: legend-color,
        stroke: black + linewidth-very-narrow,
      ),
      label: [$l = 1$],
    ),
    (
      handle: legend-handle(legend-color, markers.thin-diamond),
      label: [],
    ),
    (
      handle: legend.rectangle.with(
        fill: theory-hatch(legend-color),
        stroke: black + linewidth-very-narrow,
      ),
      label: [$l = 2$],
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: white, stroke: none))
  {
    draw.collection(..collection-11)
    draw.collection(..collection-12)
    draw.collection(..collection-15)
    draw.collection(..collection-16)
    draw.collection(..collection-19)
    draw.collection(..collection-20)
    std.place(rect(width: 39.0%, height: 100%, fill: theory-alpha-second(white)))
  }
  draw.collection(..collection-2)
  draw.collection(..collection-5)
  draw.collection(..collection-8)
  draw.line(..line-21)
  draw.line(..line-23)
  draw.line(..line-25)
  draw.line(..line-27)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.collection(..collection-4)
  draw.collection(..collection-7)
  draw.collection(..collection-10)
  draw.collection(..collection-14)
  draw.collection(..collection-18)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-3)
  draw.line(..line-6)
  draw.line(..line-9)
  draw.line(..line-13)
  draw.line(..line-17)
  axes.spines(spines)
  draw.text(..title-main)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  axes.inset-indicator(..indicator-inset-0)
  axes.inset-indicator(..indicator-inset-1)
  axes.inset-indicator(..indicator-inset-2)
  axes.inset-indicator(..indicator-inset-3)
  axes.inset(..properties-inset-0, inset-0())
  axes.inset(..properties-inset-1, inset-1())
  axes.inset(..properties-inset-2, inset-2())
  axes.inset(..properties-inset-3, inset-3())
  legend.legend(..legend-style, ..legend-items)
}


#let grid-0() = {
  let padding = (left: 11.0%, right: 1.0%, top: 39.0%, bottom: 10.0%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr,),
        rows: (1fr,),
        column-gutter: (),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
      ),
    ),
  )
}


#let figure(width: 14.24cm, height: 11.192cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#figure()
