// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *
#import "/header.typ": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node

#set page(width: 17cm, height: auto, margin: 0.9em)

#let axes-0(xlim: (-0.55, 0.55), ylim: (-17.63281841736724, 18.289186764712056), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
}


#let axes-1(xlim: (-0.55, 0.55), ylim: (-11.307772355467314, 25.615236180324544), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  draw.line(..line-0)
  draw.line(..line-1)
}


#let axes-2(xlim: (-0.55, 0.55), ylim: (-11.307772355467314, 25.615236180324544), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  draw.line(..line-0)
  draw.line(..line-1)
}


#let axes-3(xlim: (-0.55, 0.55), ylim: (-17.63281841736724, 18.289186764712056), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")

  let stroke-line-0 = (
    paint: black,
    thickness: linewidth-narrow,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-0 = none
  let line-0 = (
    data: data.at("line-0"),
    stroke: stroke-line-0,
    marker: marker-line-0,
    transform: transform,
  )

  let stroke-line-1 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-1 = none
  let line-1 = (
    data: data.at("line-1"),
    stroke: stroke-line-1,
    marker: marker-line-1,
    transform: transform,
  )

  let stroke-line-2 = (
    paint: colors(0),
    thickness: linewidth,
    cap: "butt",
    join: "round",
    dash: "solid",
  )
  let marker-line-2 = none
  let line-2 = (
    data: data.at("line-2"),
    stroke: stroke-line-2,
    marker: marker-line-2,
    transform: transform,
  )

  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
}


#let grid-0() = {
  let padding = (left: 0.694%, right: 0.695%, top: 3.788%, bottom: 3.788%)

  place(
    top + left,
    dx: padding.left,
    dy: padding.top,
    block(
      width: 100% - padding.right - padding.left,
      height: 100% - padding.top - padding.bottom,
      stroke: none,
      fill: none,
      grid(
        columns: (1fr, 1fr, 1fr, 1fr),
        rows: (1fr,),
        column-gutter: (5.07%, 5.07%, 5.07%),
        row-gutter: (),
        axes.cell(
          position: (0, 0),
          shape: (1, 1),
          axes-0(),
        ),
        axes.cell(
          position: (1, 0),
          shape: (1, 1),
          axes-1(),
        ),
        axes.cell(
          position: (2, 0),
          shape: (1, 1),
          axes-2(),
        ),
        axes.cell(
          position: (3, 0),
          shape: (1, 1),
          axes-3(),
        ),
      ),
    ),
  )
}


#let figure(width: 15.24cm, height: 2.794cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    stroke: white + 0.0pt,
    fill: white,
    grid-0(),
  )
}

#let fletcher-figure() = {
  let axes = block.with(width: 3cm, height: 2.4cm)
  let dx = 0.4
  let y0 = 0.8

  let arrow(x, width, label-bottom, label-top) = {
    edge(
      (x - width / 2, y0),
      (x + width / 2, y0),
      "-|>",
      label: text(bottom-edge: "baseline", label-bottom),
      label-sep: 0.2em,
      label-side: right,
    )
    edge(
      (x - width / 2, y0),
      (x + width / 2, y0),
      "-|>",
      stroke: none,
      label: text(bottom-edge: "baseline", label-top),
      label-sep: 0.4em,
      label-side: left,
    )
  }

  show: figure-style
  diagram(
    debug: 0,
    spacing: 0.5cm,
    edge-stroke: linewidth-very-narrow,
    node-shape: rect,
    mark-scale: 0.9,

    node((0, 0), axes(axes-0()), name: <axes-0>),
    node((1, 0), axes(axes-1()), name: <axes-1>),
    node((2, 0), axes(axes-2()), name: <axes-2>),
    node((3, 0), axes(axes-3()), name: <axes-3>),

    arrow(0.5, 0.7, "Initialization", $- pi slash 4 -> phase$),
    arrow(1.5, 0.7, "Time evolution", $ketL -> phy.ket(psi(tau0))$),
    arrow(2.5, 0.7, "Projection", $phase -> -pi slash 4$),
  )
}

#figure()
#pagebreak()
#fletcher-figure()

